export const menuItems = [
  { id: 1, label: "PENGURUSAN HAL EHWAL MURID (HEM)" },
  { id: 2, label: "GURU TINGKATAN DAN PENGURUSAN BILIK DARJAH" },
  { id: 3, label: "KAREKTOR MURID JOHOR" },
  { id: 4, label: "PERHIMPUNAN DAN PENGUMUMAN HARIAN" },
  { id: 5, label: "STUDENT LEADER BOARD" },
  { id: 6, label: "BULI DAN GANGGUAN SEKSUAL" },
  { id: 7, label: "SKIM PINJAMAN BUKU TEKS (SPBT)" },
  { id: 8, label: "UNIT DAN SISTEM MAKLUMAT HEM" },
  { id: 9, label: "BIASISWA DAN BANTUAN MURID" },
  { id: 10, label: "3K (KESELAMATAN, KESIHATAN DAN KECERIAAN)" },
  { id: 11, label: "PENGURUSAN DISIPLIN MURID" },
  { id: 12, label: "UNIT BIMBINGAN DAN KAUNSELING" },
  { id: 13, label: "SURAU AR-RASYIDIN" },
  { id: 14, label: "PENGURUSAN ASRAMA" },
  { id: 15, label: "SUMUR DAN BADAR" },
];

export const committeeData = {
  1: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi 1", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "Setiausaha Pengurusan Hal Ehwal Murid", name: "Norliyana binti Mhd. Amin" },
    { role: "AJK", position: "Guru Disiplin", name: "Salman bin A Rahman" },
    { role: "AJK", position: "Penyelaras MPP dan Lembaga Pengawas", name: "Мohammad Firros Bin Rosool Gani" },
    { role: "AJK", position: "Penyelaras Perhimpunan dan Pengumuman Harian", name: "Nor Azean binti Ismail" },
    { role: "AJK", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
    { role: "AJK", position: "Guru Biasiswa dan Bantuan Murid", name: "Annur Ayuni binti Mohamed" },
    { role: "AJK", position: "Penyelaras SUMUR", name: "Saemah binti Supandi" },
    { role: "AJK", position: "Penyelaras SPBT", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
    { role: "AJK", position: "Pengurusan Kantin", name: "Islahuddin bin Muchtar" },
    { role: "AJK", position: "Pengurusan Pencegahan Jenayah, Dadah dan Denggi", name: "Mohd Nur bin Ahmad" },
    { role: "AJK", position: "Pengurusan 3K  (Kesihatan, Kebersihan & keselamatan)", name: "Mohd Nor bin Salikin" },
    { role: "AJK", position: "Pengurusan Unit Pendaftaran dan Rekod", name: "Nurulashiqin binti Razali" },
    { role: "AJK", position: "Pengurusan Unit Data (IDME)", name: "Noorlela binti Zainudin" },
    { role: "AJK", position: "Ketua Warden", name: "Salman bin A Rahman" },
  ],
  2: [
    { role: "1 Al-Hanafi", position: "Guru Kelas", name: "Мohammad Firros Bin Rosool Gani" },
    { role: "1 Al-Syafie", position: "Guru Kelas", name: "Nurul Syafiqah binti Husin" },
    { role: "1 Al-Maliki", position: "Guru Kelas", name: "Syahidatun Najihah binti Aziz" },
    { role: "2 Al-Hanafi", position: "Guru Kelas", name: "Siti Nurul Liza binti Sidin" },
    { role: "2 Al-Syafie", position: "Guru Kelas", name: "Masyitah binti Razali" },
    { role: "2 Al-Maliki", position: "Guru Kelas", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
    { role: "3 Al-Hanafi", position: "Guru Kelas", name: "Nor Hidayah binti Mahadun" },
    { role: "3 Al-Syafie", position: "Guru Kelas", name: "Mohd Nur bin Ahmad" },
    { role: "3 Al-Maliki", position: "Guru Kelas", name: "Siti Aminah binti Mohamed" },
    { role: "4 Al-Hanafi", position: "Guru Kelas", name: "Nik Noorizati binti Ab Kahar" },
    { role: "4 Al-Syafie", position: "Guru Kelas", name: "Annur Ayuni binti Mohamed" },
    { role: "5 Al-Hanafi", position: "Guru Kelas", name: "Norashidah binti A Wahab" },
    { role: "5 Al-Syafie", position: "Guru Kelas", name: "Nurul Izzati binti Roslin" },
    { role: "Penyelaras Tahfiz", position: "Penyelaras", name: "Salman bin A Rahman" },
  ],
  3: [
    { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Timbalan Pengerusi 1", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Timbalan Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Penyelaras", position: "-", name: "Мohammad Firros Bin Rosool Gani" },
    { role: "Setiausaha", position: "-", name: "Muhammad Hafiz bin Jalil" },
    { role: "AJK", position: "-", name: "Salman bin A Rahman" },
    { role: "AJK", position: "-", name: "Nik Noorizati binti Ab Kahar" },
    { role: "AJK", position: "-", name: "Nooraind binti Ali" },
    { role: "AJK", position: "-", name: "Zarith Najiha binti Jamal" },
  ],
  4: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "Setiausaha Jawatankuasa Perhimpunan dan Pengumuman Harian", name: "Nor Azean binti Ismail" },
    { role: "AJK", position: "Pengurusan A. Sistem / Fotografi / Tayangan", name: "Mohd Nur bin Ahmad" },
    { role: "AJK", position: "Lembaga Pengawas", name: "AJK Pengawas" },
    { role: "AJK", position: "Pengurusan Pengacaraan", name: "Siti Aminah binti Mohamed" },
    { role: "AJK", position: "Pengurusan Hadiah", name: "Zarith Najiha binti Jamal" },
    { role: "AJK", position: "Ketua Pencatat", name: "Guru Bertugas Mingguan" },
  ],
  5: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi 1", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "Guru Pembimbing Rakan Sebaya (PRS)", name: "Muhammad Hafiz bin Jalil" },
    { role: "AJK", position: "Guru Penyelaras Pengawas Sekolah", name: "Мohammad Firros Bin Rosool Gani" },
    { role: "AJK", position: "Guru Penyelaras Pengawas Kelas", name: "Nik Noorizati binti Ab Kahar" },
    { role: "AJK", position: "Guru Penyelaras Pengawas Pusat Sumber", name: "Nuurul Amira binti Razak" },
    { role: "AJK", position: "Guru Penyelaras Pengawas SPBT", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
  ],
  6: [
    { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Timbalan Pengerusi 1", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Timbalan Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
    { role: "AJK", position: "Guru Disiplin", name: "Salman bin A Rahman" },
    { role: "AJK", position: "Penyelaras MPP dan Lembaga Pengawas", name: "Мohammad Firros Bin Rosool Gani" },
    { role: "AJK", position: "Ketua Warden", name: "Salman bin A Rahman" },
    { role: "AJK", position: "Semua Guru Mata Pelajaran", name: "-" },
    { role: "AJK", position: "Semua GKMP / Panitia", name: "-" },
    { role: "AJK", position: "Semua Ibu Bapa Penjaga", name: "-" },
  ],
  7: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi 1", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Penyelaras", position: "Penyelaras SPBT", name: "Masyitah binti Razali" },
    { role: "Pen. Penyelaras", position: "-", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
    { role: "AJK", position: "Semua Guru Kelas / Guru MP / Penyelaras", name: "-" },
  ],
  8: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Penyelaras", position: "Guru Data", name: "Noorlela binti Zainudin" },
    { role: "AJK", position: "Pengurusan IDME", name: "Noorlela binti Zainudin" },
    { role: "AJK", position: "Kehadiran Harian (APDM) & Enrolmen", name: "Nurulashiqin binti Razali" },
    { role: "AJK", position: "Pendaftaran, Pertukaran Dan Berhenti", name: "Yati binti Ani" },
    { role: "AJK", position: "Pengurusan SSDM Online / IDME", name: "Salman bin A Rahman" },
  ],
  9: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Setiausaha", position: "Guru Biasiswa dan Bantuan Murid", name: "Annur Ayuni binti Mohamed" },
    { role: "AJK", position: "Semua Guru Kelas / Penyelaras", name: "Semua Terlibat" },
  ],
  10: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Penyelaras", position: "Pengurusan 3K (Kesihatan & Kebersihan)", name: "Mohd Nor bin Salikin" },
    { role: "AJK", position: "Prog. Kesihatan / Covid-19", name: "Mohd Nur bin Ahmad" },
    { role: "AJK", position: "Pengurusan Kantin", name: "Islahuddin bin Muchtar" },
    { role: "AJK", position: "Pencegahan Jenayah, Dadah & Denggi", name: "Mohd Nur bin Ahmad" },
    { role: "AJK", position: "Pintu & Pagar Masuk Sekolah", name: "Pengawal Keselamatan" },
    { role: "AJK", position: "Penyelenggaraan Semula", name: "Islahuddin bin Muchtar" },
    { role: "AJK", position: "Perhubungan Luar", name: "Ali bin A Rahman" },
  ],
  11: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Setiausaha", position: "Guru Disiplin", name: "Salman bin A Rahman" },
    { role: "Naib Setiausaha", position: "Guru Pembantu Disiplin", name: "Mohamad Sukri bin Ali" },
    { role: "AJK", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
    { role: "AJK", position: "Ketua Warden", name: "Salman bin A Rahman" },
    { role: "AJK", position: "Pengerusi PIBG", name: "Ali bin Supandi" },
    { role: "AJK", position: "SU PIBG / SU PIBK", name: "Siti Nurul Liza / Mazuin Mat" },
    { role: "AJK", position: "Semua GKMP / Guru Kelas", name: "-" },
  ],
  12: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Setiausaha", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
    { role: "AJK", position: "Guru Disiplin", name: "Salman bin A Rahman" },
    { role: "AJK", position: "Semua GKMP / KP / Penyelaras", name: "-" },
    { role: "AJK", position: "Semua Guru Tingkatan", name: "-" },
  ],
  13: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi 1", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Timbalan Pengerusi 2", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Timbalan Pengerusi 3", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "Setiausaha Jawatankuasa Surau Ar-Rasyidin", name: "Mohamad Sukri bin Ali" },
    { role: "Naib Setiausaha", position: "Naib Setiausaha Jawatankuasa Surau", name: "Saemah binti Supandi" },
    { role: "Bendahari", position: "Bendahari Jawatankuasa Surau", name: "Muhammad Zaid bin Zamzuri" },
    { role: "AJK Biro", position: "Dakwah & Kerohanian", name: "Salman / Masyitah" },
    { role: "AJK Biro", position: "Multimedia & Penerbitan", name: "Mohd Nur / Nor Hidayah" },
    { role: "AJK Biro", position: "Disiplin & Keselamatan", name: "Mohd Nor / Zarith Najiha" },
    { role: "AJK Biro", position: "Kebersihan & Kebajikan", name: "Siti Aminah / Siti Nurul Liza" },
    { role: "AJK Biro", position: "Keceriaan", name: "Ahmad Fikruddin / Mazuin Mat" },
  ],
  14: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "Ketua Warden", name: "Salman bin A Rahman" },
    { role: "AJK", position: "Penyelia Asrama", name: "Islahuddin bin Muchtar" },
    { role: "AJK", position: "Warden Aspura", name: "Mohd Nor bin Salikin" },
    { role: "AJK", position: "Warden Aspuri 1 & 2", name: "Zarith / Norashidah" },
    { role: "AJK", position: "Guru B&K / Disiplin", name: "Muhammad Hafiz / Salman" },
  ],
  15: [
    { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Penyelaras", position: "Penyelaras SUMUR", name: "Saemah binti Supandi" },
    { role: "Setiausaha", position: "Setiausaha Jawatankuasa SUMUR dan BADAR", name: "Siti Aminah binti Mohamed" },
    { role: "AJK", position: "Usrah / Jati Diri", name: "Masyitah / Syahidatun" },
    { role: "AJK", position: "Budi Bahasa / Penampilan", name: "Annur Ayuni / Zarith" },
    { role: "AJK", position: "Al-Quran & Tahfiz", name: "Salman bin A Rahman" },
    { role: "AJK", position: "Warden", name: "Semua Warden" },
  ]
};

export const tasksData = {
  1: ["Mengadakan mesyuarat sekurang-kurang dua (2) kali setahun.", "Menentukan dasar dan hala tuju pengurusan hal ehwal murid sekolah.", "Merancang dan mengurus pengoperasian hal ehwal murid di sekolah.", "Merancang dan mengawal pengurusan sumber berkaitan hal ehwal murid.", "Mengenal pasti dan menyelesaikan isu dan permasalahan berkaitan murid.", "Merancang, memantau, menilai dan menambahbaik pelaksanaan program HEM.", "Membina hubungan seranta dengan ibu bapa, komuniti dan pihak berkepentingan.", "Melapor dan mendokumenkan program dan aktiviti HEM.", "Mengurus dan menyelia pengoperasian bilik-bilik khas berkaitan HEM.", "Program 3K sekolah (Keceriaan, Kebersihan, Kesihatan, Keselamatan).", "Penilaian kendiri tahap pencapaian sekolah.", "Melaksanakan tugas PPS untuk mengurus pelaporan SKPMg2."],
  2: ["Pengurusan Bilik Darjah: mewujudkan persekitaran kondusif untuk PdP.", "Peranan guru sebagai pengurus: merancang, mengelola, mengarah dan mengawal.", "Meningkatkan pelibatan murid, mengurangkan masalah disiplin & mengoptimumkan masa PdP.", "Mengemaskini kehadiran murid di APDM setiap hari sebelum pukul 12.00 tengah hari.", "Memaklumkan Penyelaras jika guru tidak hadir untuk merekod kehadiran.", "Memastikan data lengkap, sempurna dan dikemaskini (APDM).", "Menyelaras nama murid mengikut tingkatan.", "Memaklumkan murid berpindah untuk dihapuskan.", "Mendaftar murid baru dalam APDM dalam tempoh 3 hari.", "Mematuhi SOP Surat Amaran Ponteng.", "Mengurus Buku Kawalan Kelas.", "Mengurus perabot, peralatan, keceriaan dan kebersihan kelas.", "Mengurus Sijil Berhenti murid sebaik sahaja murid berhenti.", "Memaklumkan ibu bapa segera jika murid tidak hadir.", "Mengemaskini maklumat dan dokumen murid setiap akhir tahun.", "Mengurus peminjaman dan pemulangan buku teks murid."],
  3: ["Menyelaraskan Pelaksanaan Program KrMJ (Budaya bersalam, pemakaian baju T, gaya rambut).", "Membentuk Sahsiah dan Disiplin melalui modul nilai murni.", "Membina Identiti Johor (Bangsa Johor).", "Membangunkan Kepimpinan Murid yang tinggi.", "Melaksanakan Aktiviti Fizikal/Budaya (senamrobik KrMJ, bicarawara Jauhar, amalan berdoa).", "Pemantauan dan Penilaian keberkesanan program."],
  4: ["Memastikan 100% susunan murid mengikut kelas.", "Memastikan set P.A. Sistem yang disediakan berfungsi dengan baik.", "Mengelola perhimpunan harian dan mingguan.", "Mengatur semua susunan acara dengan betul.", "Memastikan laporan dan dokumentasi / fotografi semasa perhimpunan.", "Mencatat laporan perhimpunan di dalam buku bertugas mingguan.", "Membimbing murid mengendalikan perhimpunan sekolah.", "Menggunakan P.A. Sistem dengan betul semasa pengumuman."],
  5: ["Memilih dan melantik barisan pengawas.", "Merancang dan melaksanakan Program Pembangunan dan Kepimpinan Pengawas.", "Menyusun dan memantau semua tugas harian pengawas.", "Mengadakan satu taklimat dan perjumpaan pengawas setiap minggu.", "Membuat laporan pengawas setiap minggu.", "Memastikan pengawas mematuhi peraturan dan undang-undang sekolah.", "Mengurus satu Kursus Kepimpinan Pengawas kepada semua pengawas."],
  6: ["Merancang dan melaksanakan program kesedaran buli dan gangguan seksual (ceramah, seminar, kempen).", "Mengawasi persekitaran sekolah untuk mengesan tanda buli atau gangguan seksual.", "Menyiasat aduan dengan teliti, mendokumenkan bukti dan tindakan disiplin.", "Memberikan bimbingan dan sokongan emosi kepada mangsa serta pelaku.", "Menyediakan laporan berkala dan cadangan penambahbaikan polisi."],
  7: ["Memastikan semua murid menerima SPBT sebelum hari pertama persekolahan.", "Mengurus semua proses pemulangan SPBT.", "Mengambil tindakan terhadap murid yang gagal memulangkan buku teks.", "Mengemaskini data / stok SPBT.", "Menghantar laporan ke PPD / JPN menepati arahan.", "Mengadakan aktiviti baik pulih buku teks.", "Menceriakan bilik BOSS.", "Menjalankan ‘spot check’ kepada murid berkenaan penggunaan buku teks."],
  8: ["Memastikan semua data murid terdapat di dalam sistem mengikut keperluan.", "Merekod salah laku murid dalam tempoh 3 hari.", "Menghantar laporan ke PPD / JPN pada setiap awal bulan.", "Menganalisis laporan bulanan untuk tujuan Audit Disiplin."],
  9: ["Mengenal pasti bilangan murid yang layak mengikut kriteria.", "Mengurus semua permohonan BKP /KWAPM/ bantuan menepati pelan tindakan.", "Mengurus dan memantau pengeluaran wang penerima.", "Mendidik penerima tentang penggunaan bantuan dengan cara yang betul.", "Memantau perkembangan akademik penerima.", "Mencari maklumat murid yang perlu bantuan.", "Mengurus permohonan bantuan kebajikan HEM / PIBG."],
  10: ["Mengenal pasti potensi lokasi bahaya dan kemalangan.", "Menyediakan polisi keselamatan dan disebar luas kepada warga sekolah.", "Penarafan Keselamatan Sekolah.", "Menguruskan buku / maklumat kesihatan dan pemeriksaan gigi/suntikan.", "Program Promosi Kesihatan dan Minggu Anti Dadah.", "Pemajuan sekolah sifar vandalisma.", "Menyelaras pertandingan keceriaan kelas.", "Memastikan kawasan sekolah ceria, bersih dan bersih."],
  11: ["Merancang dan mengurus hal disiplin murid (Semua guru ialah guru disiplin).", "Pendedahan cara mengenal pasti murid berisiko dalam kelas.", "Mewujudkan iklim suasana harmoni, akrab serta selesa di sekolah.", "Menggubal dan menyediakan peraturan sekolah.", "Membantu guru bertugas harian menjaga disiplin.", "Pengurusan Murid Berisiko Cicir bersama UBK dan PIBG.", "Mengemaskinikan maklumat SSDM."],
  12: ["Menguruskan satu Kursus Kepimpinan Pengawas, PRS, SLB dan Ketua Tingkatan.", "Program Peningkatan Sahsiah Murid (ponteng, merokok, dadah, akhlak).", "Melaksanakan Program Motivasi dan aktiviti kaunseling individu/kelompok.", "Memastikan murid didedahkan kemahiran belajar sebelum bulan Mac.", "Badan perhubungan PIBG, PIBK, NGO, dan IPT dalam menangani isu ponteng.", "Merancang Program Pembangunan Sahsiah dan Kerohanian Murid."],
  13: ["PENTADBIRAN: Logo, misi/visi, organisasi, takwim, jadual bertugas, adab & peraturan surau.", "KEWANGAN: Menyediakan buku tunai.", "REKOD: Buku pelawat, penggunaan, pemantauan, pinjaman dan peralatan.", "PENGIMARAHAN: Solat, tilawah, tadarus, zikir, Imam/Bilal remaja, usrah.", "KELENGKAPAN: PA Sistem, rehal, rak, jam, kiblat, tv.", "FIZIKAL: Bangunan, khat, tempat wuduk, tandas, lampu, kipas.", "KESELAMATAN: Peti kecemasan, pemadam api dan pelan kebakaran.", "LAPORAN: Instrumen penarafan surau imarah sekolah-sekolah (PERSISS-j)."],
  14: ["Mengatur pembahagian tugas di asrama.", "Memastikan pengurusan asrama bejalan lancar mengikut ketetapan kementerian.", "Merancang aktiviti asrama mengikut garis panduan kementerian.", "Memastikan peraturan asrama dipatuhi.", "Meningkatkan hubungan jawatankuasa asrama dengan ibu bapa / penjaga.", "Menyusun jadual penyeliaan asrama."],
  15: ["SUMUR/Sahsiah: Merancang program kerohanian, hari kebesaran Islam & Ramadhan.", "SETIAUSAHA: Minit mesyuarat, laporan aktiviti tahunan & data sistem SUMUR.", "USRAH & BADAR: Organisasi usrah, Liqa’ Nuqaba’, pelantikan & penilaian murabbi.", "BUDI BAHASA/JATI DIRI: Majlis pelancaran & program bertema.", "MUTADAYYIN: Menyelaras program keislaman & kerohanian.", "MUSOLLA: Mengimarahkan surau sebagai pusat ibadah.", "AL-QURAN & TAHFIZ: Program membudayakan Al-Quran, Ulul Albab & Isbat Tahfiz."]
};
