export const menuItems = [
  { id: 1, label: "PENGURUSAN SEKOLAH" },
  { id: 2, label: "PENGURUSAN PROGRAM KECEMERLANGAN SEKOLAH" },
  { id: 3, label: "PENGURUSAN PERSEKITARAN DAN KEMUDAHAN FIZIKAL" },
  { id: 4, label: "KELAB KEBAJIKAN GURU DAN KAKITANGAN" },
  { id: 5, label: "PENGURUSAN KEWANGAN, AKAUN DAN ASET SEKOLAH" },
  { id: 6, label: "PENGURUSAN DAN KEPIMPINAN ORGANISASI" },
  { id: 7, label: "TAKWIM DAN BUKU PENGURUSAN SEKOLAH" },
  { id: 8, label: "KHAIRIAH DIGITAL EDU HUB" },
  { id: 9, label: "PENGURUSAN MAKLUMAT SEKOLAH" },
  { id: 10, label: "PENGURUSAN SUMBER MANUSIA" },
  { id: 11, label: "STANDARD KUALITI PENDIDIKAN MALAYSIA" },
  { id: 12, label: "PENGURUSAN BENCANA SEKOLAH" },
  { id: 13, label: "PERHUBUNGAN LUAR" },
  { id: 14, label: "KAJIAN TINDAKAN DAN INOVASI" },
  { id: 15, label: "PENGURUSAN KEWANGAN SEKOLAH" },
  { id: 16, label: "PENGURUSAN ASET ALIH KERAJAAN" },
];

export const committeeData = {
  1: [
      { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Tim. Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Naib Pengerusi 1", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
      { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Setiausaha", position: "Setiausaha Pengurusan Pentadbiran", name: "Nooraind binti Ali" },
      { role: "AJK", position: "GKMP Agama", name: "Saemah binti Supandi" },
      { role: "AJK", position: "GKMP Dini", name: "Nor Azean binti Ismail" },
      { role: "AJK", position: "GKMP Bahasa", name: "Rosmawati @ Rohayati binti Hussin" },
      { role: "AJK", position: "GKMP Kemanusiaan", name: "Nooraind binti Ali" },
      { role: "AJK", position: "GKMP Sains & Matematik", name: "Zahrah Khairiah Nasution binti Saleh" },
      { role: "AJK", position: "GKMP Teknik & Vokasional", name: "Mazuin binti Mat" },
      { role: "AJK", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
      { role: "AJK", position: "Guru Perpustakaan & Media", name: "Nuurul Amira binti Razak" },
      { role: "AJK", position: "Guru Data", name: "Noorlela binti Zainudin" },
      { role: "AJK", position: "Penyelaras ICT/DELIMA", name: "Syahidatun Najihah binti Aziz" },
      { role: "AJK", position: "Guru Disiplin", name: "Salman bin A Rahman" },
      { role: "AJK", position: "Penyelaras Program TS25", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
      { role: "AJK", position: "Penyelia Asrama", name: "Islahuddin bin Muchtar" },
      { role: "AJK", position: "Ketua Anggota Kumpulan Pelaksana", name: "Yati binti Ani" },
      { role: "AJK", position: "Ketua Warden", name: "Salman bin A Rahman" },
  ],
  2: [
      { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Tim. Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
      { role: "Naib Pengerusi", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Penyelaras", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
      { role: "AJK", position: "Semua GKMP", name: "-" },
      { role: "AJK", position: "Semua Ketua Panitia", name: "-" },
      { role: "Penyelaras Tingkatan 1", position: "-", name: "Мohammad Firros bin Rosool Gani" },
      { role: "Penyelaras Tingkatan 2", position: "-", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
      { role: "Penyelaras Tingkatan 3", position: "-", name: "Siti Aminah binti Mohamed" },
      { role: "Penyelaras Tingkatan 4", position: "-", name: "Nik Noorizati binti Ab Kahar" },
      { role: "Penyelaras Tingkatan 5", position: "-", name: "Norashidah binti A Wahab" },
      { role: "Penyelaras Tahfiz Al-Syatibi", position: "-", name: "Salman bin A Rahman" },
  ],
  3: [
      { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Timbalan Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Naib Pengerusi 1", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
      { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Setiausaha", position: "Setiausaha Pengurusan Persekitaran & Kemudahan Fizikal", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Pengetua dan Penolong Kanan", name: "Yati binti Ani" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Pentadbiran", name: "Nurulashiqin binti Razali" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Pencetakan", name: "Sadan bin Md Seth" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Operasi Peperiksaan", name: "Annur Ayuni binti Mohamed" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Badan Perwakilan Murid (SLB)", name: "Nik Noorizati binti Ab Kahar" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Kaunseling", name: "Muhammad Hafiz bin Jalil" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Gerakan Asrama", name: "Islahuddin bin Muchtar" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Mesyuarat", name: "Mazuin binti Mat" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik SPBT", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik GKMP", name: "Rosmawati @ Rohayati binti Hussin" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Guru", name: "Masyitah binti Razali" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik RBT", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Komputer", name: "Syahidatun Najihah binti Aziz" },
      { role: "AJK Pengurus", position: "Pengurusan Bilik Makmal Sains", name: "Nur Farhana binti Hassan" },
      { role: "AJK Pengurus", position: "Pengurusan Perpustakaan", name: "Nuurul Amira binti Razak" },
      { role: "AJK Pengurus", position: "Pengurusan Dewan Besar", name: "Nor Ain binti Mohamed Jori" },
      { role: "AJK Pengurus", position: "Setiausaha Jawatankuasa Surau Ar-Rasyidin", name: "Mohd Nor bin Salikin" },
      { role: "AJK Pengurus", position: "Pengurusan Stor Sekolah", name: "Mohd Nur bin Ahmad" },
      { role: "AJK Pengurus", position: "Pengurusan Kantin", name: "Islahuddin bin Muchtar" },
      { role: "AJK Pengurus", position: "Pengurusan Kedai Sekolah", name: "Aina Izlin Syafika binti Abd Rahim" },
      { role: "AJK Pengurus", position: "Pengurusan Siaraya", name: "Mohd Nur bin Ahmad" },
      { role: "AJK Pengurus", position: "Pengurusan Bangunan / Elektrik / Paip / Perabot", name: "Islahuddin bin Muchtar" },
  ],
  4: [
      { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Pengerusi", position: "-", name: "Mohamad Sukri bin Ali" },
      { role: "Naib Pengerusi", position: "-", name: "Mazuin binti Mat" },
      { role: "Setiausaha", position: "-", name: "Norashidah binti A Wahab" },
      { role: "Bendahari", position: "-", name: "Nurulashiqin binti Razali" },
      { role: "AJK", position: "-", name: "Nur Farhana binti Hassan" },
      { role: "AJK", position: "-", name: "Nuurul Amira binti Razak" },
      { role: "AJK", position: "-", name: "Zarith Najiha binti Jamal" },
      { role: "AJK", position: "-", name: "Mohd Nor bin Salikin" },
      { role: "AJK", position: "-", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
      { role: "AJK", position: "-", name: "Muhammad Zaid bin Zamzuri" },
  ],
  5: [
      { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Timbalan Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Naib Pengerusi 1", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
      { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Setiausaha", position: "Ketua Anggota Kumpulan Pelaksana", name: "Yati binti Ani" },
      { role: "Pen. Setiausaha 1", position: "Penolong Setiausaha Akaun Sekolah 1", name: "Aina Fazrina binti Paing" },
      { role: "Pen. Setiausaha 2", position: "Penolong Setiausaha Akaun Sekolah 2", name: "Islahuddin bin Muchtar" },
      { role: "Juru Audit Dalaman 1", position: "Juru Audit Dalaman 1", name: "Norashidah binti A Wahab" },
      { role: "Juru Audit Dalaman 2", position: "Juru Audit Dalaman 2", name: "Nooraind binti Ali" },
      { role: "Pegawai Pemeriksa Aset 1", position: "Pegawai Pemeriksa Aset 1", name: "Shaharer bin Hj Husain" },
      { role: "Pegawai Pemeriksa Aset 2", position: "Pegawai Pemeriksa Aset 2", name: "Mohd Nur bin Ahmad" },
      { role: "Pegawai Pelupusan Aset 1", position: "Pegawai Pelupusan Aset 1", name: "Islahuddin bin Muchtar" },
      { role: "Pegawai Pelupusan Aset 2", position: "Pegawai Pelupusan Aset 2", name: "Mohd Nor bin Salikin" },
      { role: "AJK", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
      { role: "AJK", position: "Setiausaha Pengurusan Kurikulum Sekolah", name: "Saemah binti Supandi" },
      { role: "AJK", position: "Setiausaha Pengurusan Kokurikulum", name: "Nurul Syafiqah binti Husin" },
      { role: "AJK", position: "Setiausaha Pengurusan Sukan & Permainan", name: "Zarith Najiha binti Jamal" },
      { role: "AJK", position: "Semua GKMP", name: "-" },
      { role: "AJK", position: "Semua Ketua Panitia", name: "-" },
      { role: "AJK", position: "Semua Penyelaras Tingkatan", name: "-" },
  ],
  6: [
      { role: "Pengerusi", position: "-", name: "Zulkeffle bin Muhammad" },
      { role: "Timbalan Pengerusi (Pengurus Kualiti)", position: "-", name: "Noratikah binti Abd. Kadir" },
      { role: "Setiausaha (Penyelaras Pelan Strategik)", position: "-", name: "Zahrah Khairiah Nasution binti Saleh" },
      { role: "Ahli Jawatankuasa", position: "-", name: "Shaharer bin Hj Husain" },
      { role: "Ahli Jawatankuasa", position: "-", name: "Zulkifli bin Md Aspan" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK01 (Pengurusan Panitia)", name: "Nor Azean binti Ismail" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK02 (Pengurusan Jadual Waktu)", name: "Salman bin A Rahman" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK03 (Pengurusan Pembelajaran & Pemudahcaraan)", name: "Saemah binti Supandi" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK04 (Pengurusan Pencerapan)", name: "Rosmawati @ Rohayati binti Hussin" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK05 (Pengurusan Penilaian & Pentaksiran)", name: "Annur Ayuni binti Mohamed" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK06 (Pengurusan Semakan Hasil Kerja Murid)", name: "Mohamad Nasreen Hakim bin Che Mohamed" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK07 (Pengurusan Mesyuarat)", name: "Nooraind binti Ali" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK08 (Pengurusan Aduan & Maklum Balas Pelanggan)", name: "Masyitah binti Razali" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK09 (Pengurusan Pusat Sumber)", name: "Nuurul Amira binti Razak" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK10 (Pengurusan Latihan Personel)", name: "Liyana binti Iskandar" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK11 (Pengurusan Perolehan dan Pembelian)", name: "Yati binti Ani" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK12 (Peng. Kawalan Dokumen & Rekod Kualiti)", name: "Islahuddin bin Muchtar" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK13 (Pengurusan Bimbingan & Kaunseling)", name: "Muhammad Hafiz bin Jalil" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK14 (Pengurusan Audit Dalaman)", name: "Norashidah binti A Wahab" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK15 (Pengurusan Kawalan Ketidak Akuran)", name: "Shaharer bin Hj Husain" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK16 (Pengurusan Tindakan Pembetulan, Pencegahan dan Penambahbaikan)", name: "Shaharer bin Hj Husain" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK17 (Pengurusan Kajian Semula Pengurusan)", name: "Shaharer bin Hj Husain" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK18 (Pengurusan Pentaksiran Kokurikulum)", name: "Nurul Syafiqah binti Husin" },
      { role: "Penyelaras Prosedur Kualiti", position: "PK19 (Pengurusan Sukan dan Permainan)", name: "Zarith Najiha binti Jamal" },
  ],
  7: [
      { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Timbalan Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Naib Pengerusi 1", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
      { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Setiausaha", position: "Guru Data", name: "Noorlela binti Zainudin" },
      { role: "Timbalan Setiausaha", position: "Pembantu Editor", name: "Nor Azean binti Ismail" },
      { role: "AJK", position: "Setiausaha Pengurusan Pentadbiran", name: "Nooraind binti Ali" },
      { role: "AJK", position: "Setiausaha Pengurusan Kurikulum Sekolah", name: "Saemah binti Supandi" },
      { role: "AJK", position: "Setiausaha Pengurusan Hal Ehwal Murid", name: "Norliyana binti Mhd. Amin" },
      { role: "AJK", position: "Setiausaha Pengurusan Kokurikulum", name: "Nurul Syafiqah binti Husin" },
      { role: "AJK", position: "Setiausaha Pengurusan Sukan & Permainan", name: "Zarith Najiha binti Jamal" },
      { role: "AJK", position: "Setiausaha Jadual Waktu", name: "Mohamad Nasreen Hakim bin Che Mohamed" },
      { role: "AJK", position: "Penyelia Asrama", name: "Islahuddin bin Muchtar" },
  ],
  8: [
      { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Setiausaha", position: "Setiausaha Smart Digital Hub", name: "Noorlela binti Zainudin" },
      { role: "Penyelaras", position: "Penyelaras Smart Digital Hub", name: "Syahidatun Najihah binti Aziz" },
      { role: "AJK", position: "Setiausaha Pengurusan Pentadbiran", name: "Nooraind binti Ali" },
      { role: "AJK", position: "Setiausaha Pengurusan Kurikulum Sekolah", name: "Saemah binti Supandi" },
      { role: "AJK", position: "Setiausaha Pengurusan Hal Ehwal Murid", name: "Norliyana binti Mhd. Amin" },
      { role: "AJK", position: "Setiausaha Pengurusan Kokurikulum", name: "Nurul Syafiqah binti Husin" },
      { role: "AJK", position: "Setiausaha Pengurusan Sukan & Permainan", name: "Zarith Najiha binti Jamal" },
      { role: "AJK", position: "Semua GKMP", name: "-" },
      { role: "AJK", position: "Semua KP", name: "-" },
      { role: "AJK", position: "Semua Guru Mata Pelajaran", name: "-" },
      { role: "AJK", position: "Asrama", name: "Islahuddin bin Muchtar" },
  ],
  9: [
      { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Tim. Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Naib Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
      { role: "Naib Pengerusi", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Setiausaha", position: "Guru Data", name: "Noorlela binti Zainudin" },
      { role: "Pen. Setiausaha", position: "Ketua Anggota Kumpulan Pelaksana", name: "Yati binti Ani" },
      { role: "AJK", position: "Pengurusan Aset & Inventori", name: "-" },
      { role: "AJK", position: "Penyelaras SPBT", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
      { role: "AJK", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
      { role: "AJK", position: "Guru Perpustakaan & Media", name: "Nuurul Amira binti Razak" },
      { role: "AJK", position: "Guru Penyelaras ICT/DELIMA", name: "Syahidatun Najihah binti Aziz" },
      { role: "AJK", position: "Guru Biasiswa dan Bantuan Murid", name: "Annur Ayuni binti Mohamed" },
      { role: "AJK", position: "Guru Disiplin", name: "Salman bin A Rahman" },
      { role: "AJK", position: "Setiausaha Pengurusan Pentadbiran", name: "Nooraind binti Ali" },
      { role: "AJK", position: "Setiausaha Pengurusan Kurikulum Sekolah", name: "Saemah binti Supandi" },
      { role: "AJK", position: "Setiausaha Pengurusan Kokurikulum", name: "Nurul Syafiqah binti Husin" },
      { role: "AJK", position: "Setiausaha JK Standard Kualiti Pendidikan Malaysia", name: "Zahrah Khairiah Nasution binti Saleh" },
      { role: "AJK", position: "Setiausaha Jadual Waktu", name: "Mohamad Nasreen Hakim bin Che Mohamed" },
      { role: "AJK", position: "Penyelaras Peperiksaan Dalaman Sekolah", name: "Annur Ayuni binti Mohamed" },
      { role: "AJK", position: "Penyelia Asrama", name: "Islahuddin bin Muchtar" },
      { role: "AJK", position: "Pengurusan Semakan Kehadiran Guru & AKP", name: "Nurulashiqin binti Razali" },
      { role: "AJK", position: "Semua GKMP", name: "-" },
      { role: "AJK", position: "Semua Ketua Bilik-bilik Khas", name: "-" },
  ],
  10: [],
  11: [
      { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Timb. Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Naib Pengerusi 1", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
      { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Setiausaha", position: "Setiausaha JK Standard Kualiti Pendidikan Malaysia", name: "Zahrah Khairiah Nasution binti Saleh" },
      { role: "AJK", position: "Setiausaha Pengurusan Pentadbiran", name: "Nooraind binti Ali" },
      { role: "AJK", position: "Setiausaha Pengurusan Kurikulum Sekolah", name: "Saemah binti Supandi" },
      { role: "AJK", position: "Setiausaha Pengurusan Hal Ehwal Murid", name: "Norliyana binti Mhd. Amin" },
      { role: "AJK", position: "Setiausaha Pengurusan Kokurikulum", name: "Nurul Syafiqah binti Husin" },
      { role: "AJK", position: "Setiausaha Pengurusan Sukan & Permainan", name: "Zarith Najiha binti Jamal" },
      { role: "AJK", position: "Guru Data", name: "Noorlela binti Zainudin" },
  ],
  12: [
      { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Tim. Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Naib Pengerusi 1", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
      { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Penyelaras", position: "Penyelaras Bencana", name: "Mazuin binti Mat" },
      { role: "AJK", position: "Semua GKMP", name: "-" },
      { role: "AJK", position: "Semua Ketua Panitia", name: "-" },
      { role: "AJK", position: "Semua Guru Mata Pelajaran", name: "-" },
      { role: "AJK", position: "Semua Ibu Bapa Penjaga", name: "-" },
      { role: "AJK", position: "Semua Murid", name: "-" },
  ],
  13: [
      { role: "Ketua Penaung Lembaga Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Lembaga Penasihat", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Lembaga Penasihat", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
      { role: "Lembaga Penasihat", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Yang Dipertua PIBG", position: "-", name: "Mohd Ali bin Supandi" },
      { role: "Naib Yang Dipertua PIBG", position: "-", name: "Haslinda binti Ayzar" },
      { role: "Setiausaha", position: "Setiausaha Persatuan Ibu Bapa Guru (PIBG)", name: "Siti Nurul Liza binti Sidin" },
      { role: "Setiausaha", position: "Setiausaha Penglibatan Ibu Bapa & Komuniti (PIBK)", name: "Mazuin binti Mat" },
      { role: "Penolong Setiausaha", position: "-", name: "Nurfazira binti Dolah" },
      { role: "Bendahari", position: "-", name: "Norliyana Binti Mhd Amin" },
      { role: "AJK", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
      { role: "Juru Audit Dalaman", position: "Guru", name: "Nik Noorizati binti Ab Kahar" },
      { role: "Juru Audit Dalaman", position: "Ibu Bapa", name: "Farah Nizar binti Abdullah" },
      { role: "AJK Ibu Bapa", position: "-", name: "Zulhairi bin Ab Kadir" },
      { role: "AJK Ibu Bapa", position: "-", name: "Ros bin Hashim" },
      { role: "AJK Ibu Bapa", position: "-", name: "Rozita binti Abd Razak" },
      { role: "AJK Ibu Bapa", position: "-", name: "Rahimah binti Ali" },
      { role: "AJK Guru", position: "-", name: "Saemah binti Supandi" },
      { role: "AJK Guru", position: "-", name: "Nor Hidayah binti Mahadun" },
      { role: "AJK Guru", position: "-", name: "Ahmad Fiqrudin bin Ahmad Razai '" },
      { role: "AJK Guru", position: "-", name: "Mohd Nor bin Salikin" },
      { role: "AJK Guru", position: "-", name: "Nuurul Amira binti Razak" },
      { role: "AJK PIBK", position: "-", name: "Esbolah bin Sahadon" },
      { role: "AJK PIBK", position: "-", name: "Norliyana binti Abu" },
      { role: "AJK PIBK", position: "-", name: "Mazuin binti Mat" },
  ],
  14: [
      { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Tim. Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Naib Pengerusi 1", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
      { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Penyelaras & Setiausaha", position: "Kajian Tindakan", name: "Rosmawati @ Rohayati binti Hussin" },
      { role: "Penyelaras & Setiausaha", position: "Inovasi", name: "Nor Azean binti Ismail" },
      { role: "AJK", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
      { role: "AJK", position: "GKMP Agama", name: "Saemah binti Supandi" },
      { role: "AJK", position: "GKMP Dini", name: "Nor Azean binti Ismail" },
      { role: "AJK", position: "GKMP Bahasa", name: "Rosmawati @ Rohayati binti Hussin" },
      { role: "AJK", position: "GKMP Sains & Matematik", name: "Zahrah Khairiah Nasution binti Saleh" },
      { role: "AJK", position: "GKMP Kemanusiaan", name: "Nooraind binti Ali" },
      { role: "AJK", position: "GKMP Teknik & Vokasional", name: "Mazuin binti Mat" },
      { role: "AJK", position: "Guru Disiplin", name: "Salman bin A Rahman" },
      { role: "AJK", position: "Guru Perpustakaan & Media", name: "Nuurul Amira binti Razak" },
      { role: "AJK", position: "Guru Penyelaras ICT/DELIMA", name: "Syahidatun Najihah binti Aziz" },
      { role: "AJK", position: "Guru Data", name: "Noorlela binti Zainudin" },
      { role: "AJK", position: "Semua Ketua Panitia", name: "-" },
  ],
  15: [
      { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Timbalan Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Setiausaha", position: "Ketua Anggota Kumpulan Pelaksana", name: "Yati binti Ani" },
      { role: "Pen. Setiausaha", position: "-", name: "Islahuddin bin Muchtar" },
      { role: "AJK", position: "Ketua Warden", name: "Salman bin A Rahman" },
      { role: "AJK", position: "Juru Audit Dalaman", name: "Norashidah binti A Wahab" },
      { role: "AJK", position: "Semua Warden", name: "-" },
  ],
  16: [
      { role: "Pengerusi Aset", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
      { role: "Pegawai Aset", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
      { role: "Pembantu Pegawai Aset", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
      { role: "Pegawai Pemeriksa 1", position: "Pegawai Pemeriksa 1", name: "Shaharer bin Hj Husain" },
      { role: "Pegawai Pemeriksa 2", position: "Pegawai Pemeriksa 2", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
      { role: "Pegawai Pelupusan 1", position: "Pegawai Pelupusan 1", name: "Mohd Nur bin Ahmad" },
      { role: "Pegawai Pelupusan 2", position: "Pegawai Pelupusan 2", name: "Islahuddin bin Muchtar" },
  ],
};

export const tasksData = {
  1: [
      "Mengadakan mesyuarat sekurang-kurang dua (2) kali setahun.",
      "Menentukan dasar dan hala tuju sekolah.",
      "Merancang dan mengurus pengoperasian sekolah.",
      "Merancang dan mengawal pengurusan sumber di sekolah.",
      "Mengenal pasti dan menyelesaikan isu dan permasalahan di sekolah.",
      "Merancang, memantau, menilai dan menambahbaikan pelaksanaan program dan aktiviti sekolah.",
      "Membina hubungan seranta dengan ibu bapa, komuniti dan pihak yang berkepentingan.",
      "Melapor dan mendokumenkan program dan aktiviti sekolah.",
      "Mengurus dan menyelia pengoperasian bilik khas berkaitan kurikulum.",
      "Merancang, menyusun dan melaksana program-program dan aktiviti-aktiviti untuk meningkatkan tahap pencapaian sekolah dalam bidang pengurusan, akademik, kemenjadian murid, kokurikulum dan keceriaan.",
      "Membuat penilaian kendiri tahap pencapaian sekolah berdasarkan keputusan Pelaporan Sekolah Rendah dan PBD.",
      "Melaksanakan tugas PPS di bawah komponen terlibat untuk mengurus pelaporan SKPMg2."
  ],
  2: [
      "Merancang and menyelaraskan aktiviti dan program kecemerlangan sekolah berpandukan perancangan strategik sekolah.",
      "Memastikan setiap sen yang dibelanjakan memberi impak yang tinggi dengan membuat anggaran perbelanjaan tahunan untuk setiap program kecemerlangan.",
      "Menyelia dan membuat pemantauan setiap program dilaksanakan dengan sempurnanya and berkesan.",
      "Menyediakan pelan intervensi mengikut keperluan sekolah bagi penambahbaikan program kecemerlangan.",
      "Dokumentasi/Laporan Aktiviti Sekolah: Memastikan setiap jawatankuasa program bertanggungjawab menyediakan pelaporan aktiviti masing-masing dan menyerahkan kepada pihak pengurusan dokumentasi/laporan aktiviti sekolah. Setiap jawatankuasa program tersebut perlu menyertakan: Laporan aktiviti, Laporan kewangan (Jika ada), Gambar-gambar program, Kertas kerja, Lampiran berkaitan seperti kad jemputan, sijil, buku program dan lain-lain.",
      "Memastikan papan kenyataan setiap unit dikemaskinikan dengan info dan gambar terkini secara berkala oleh unit-unit berkenaan."
  ],
  3: [
      "Merancang dan menceriakan bilik-bilik khas.",
      "Memastikan bilik sentiasa bersih dan ceria.",
      "Menyediakan carta organisasi setiap bilik.",
      "Memastikan setiap bilik dilengkapi dengan visi dan misi sekolah",
      "Memastikan bilik digunakan dengan baik dan secara maksimum.",
      "Menyediakan buku lawatan, penggunaan bilik dan buku rekod pinjaman alatan serta memastikan buku-buku tersebut digunakan secara maksimum.",
      "Menyediakan peraturan dan jadual penggunaan bilik.",
      "Memantau dan membuat laporan kepada pentadbir dari semasa dan semasa.",
      "Merancang dan melaksana program untuk menambah baik infrastruktur dan prasarana sekolah.",
      "Merancang dan melaksana aktiviti baik pulih perabot terutama kerusi dan meja murid serta kerosakan paip dan elektrik.",
      "Melaksana pemantauan terhadap keselamatan bangunan dan prasarana sekolah secara keseluruhannya.",
      "Merancang dan melaksana aktiviti meningkatkan kemudahan infrastruktur sekolah.",
      "Mengemuka dan membuat permohonan berkaitan kemudahan fizikal sekolah kepada PPD, JPN and KPM.",
      "Mengadakan mesyuarat dan mengemuka laporan bertulis atau lisan kepada Pengetua tentang segala kerosakan atau cadangan penambahbaikan."
  ],
  4: [
      "Kelab Kebajikan Guru dan Kakitangan dianggotai secara automatik oleh semua staf di sekolah. Kelab ini bertujuan untuk menjaga kebajikan dan mewujudkan hubungan harmoni dalam kalangan staf.",
      "Merancang dan mengurus aktiviti/program bagi kebajikan dan kemajuan staf sekolah.",
      "Menjadi penggerak dan pengantara yang membolehkan staf berinteraksi dan berkomunikasi dalam suasana sosial yang sihat.",
      "Mewujudkan persekitaran kerja yang kondusif dan produktif.",
      "Menyelenggarakan dan menghias susun atur di dalam bilik guru termasuk ruang kerja dan ruang rehat staf.",
      "Memastikan aktiviti/program kelab dilaksanakan dengan sempurna dan teratur seperti yang telah dirancang.",
      "Menyelaraskan dan memenuhi keperluan staf dari semasa ke semasa.",
      "Mengendalikan kutipan yuran, mengurus belanjawan aktiviti kelab dan pemberian bantuan kepada ahli yang melibatkan kebajikan ahli seperti sakit, kematian atau menunaikan haji."
  ],
  5: [
      "Bertanggungjawab untuk melaksanakan perkara berikut:",
      "Menyediakan laporan (Lampiran C, PS5.1 Garis Panduan Pelaksanaan JPKA), dibentang dan disahkan dalam mesyuarat.",
      "Mesyuarat hendaklah diadakan setiap tiga (3) bulan sekali secara berasingan atau bersekali dengan mesyuarat pengurusan yang lain di peringkat sekolah.",
      "Agenda Mesyuarat perlu merangkumi perkara berikut: Pengurusan Bajet, Pengurusan Perakaunan, Pengurusan Perolehan, Pengurusan Aset dan Stor, Prestasi Perbelanjaan Peruntukan dari Badan Berkanun Persekutuan.",
      "PGB hendaklah memastikan JK mematuhi semua perkara di atas. Ketidakpatuhan pada perkara tersebut akan menyebabkan sekolah berkenaan mendapat teguran audit."
  ],
  6: [
      "Perancangan Strategik: PGB menetapkan hala tuju sekolah dengan membuat perancangan strategik.",
      "Membuat analisis secara menyeluruh merangkumi bidang kurikulum, kokurikulum dan hal ehwal murid atau warga sekolah menggunakan alat pengukur yang sesuai untuk mengenal pasti isu strategik.",
      "Pelan Strategik disediakan mengikut bidang pengurusan (9 Standard Kompetensi Kepengetuaan Sekolah Malaysia - SKKM): Pengurusan dan Kepimpinan Organisasi, Pengurusan Kurikulum, Pengurusan Hal Ehwal Murid, Pengurusan Kokurikulum, Pengurusan Kewangan, Pengurusan Pentadbiran Pejabat, Pengurusan Persekitaran dan Kemudahan Fizikal, Pengurusan dan Pembangunan Sumber Manusia, Pengurusan Perhubungan Luar.",
      "Menyebar luas hala tuju dalam bentuk tindakan yang bersesuaian kepada semua anggota organisasi sekolah.",
      "Memastikan pelan strategik dilaksanakan.",
      "Membuat semakan pencapaian objektif dan KPI serta melaksanakan penambahbaikan yang bersesuaian dari semasa ke semasa."
  ],
  7: [
      "Menyediakan takwim dan buku pengurusan sekolah sebagai panduan pengoperasian tahunan.",
      "Mengadakan mesyuarat pengurusan sekolah tugas bagi jawatankuasa kerja.",
      "Mendapatkan maklumat berkaitan dengan takwim sekolah seperti jadual peperiksaan, aktiviti kurikulum, kokurikulum dan hal ehwal murid.",
      "Mendapatkan takwim induk program dari KPM, JPN dan PPD untuk digunakan dan diselaraskan bagi tahun berkenaan.",
      "Menyelaraskan secara seimbang senarai agihan tugas kepada guru-guru dan kakitangan sekolah mengikut kompetensi/kepakaran/kesesuaian guru dan kakitangan.",
      "Melakukan proses penyuntingan, pemurnian bahan-bahan dan percetakan.",
      "Penyebaran/pengedaran takwim sekolah kepada guru dan kakitangan."
  ],
  8: [
      "Menyediakan laporan bagi setiap aktiviti sekolah.",
      "Mendokumentasikan laporan/surat/dokumen yang berkaitan.",
      "Mengemas kini maklumat dan kandungan baharu laman sesawang.",
      "Menjalankan tugas-tugas lain yang diarahkan oleh pengurusan sekolah dari semasa ke semasa.",
      "PENGURUSAN LAMAN SESAWANG SEKOLAH: Semua maklumat yang hendak dimuatkan ke dalam laman web mestilah mendapat kelulusan mengikut prosedur yang telah ditetapkan.",
      "Maklumat di laman web hendaklah dikemas kini dari semasa ke semasa.",
      "Pembangunan laman web hendaklah mempunyai ciri-ciri keselamatan bagi mengelakkan laman diceroboh dan digodam.",
      "Pembangunan laman web perlu mematuhi Pekeliling Pengurusan Laman Web Agensi Sektor Awam."
  ],
  9: [
      "Melaksanakan mesyuarat dan penghantaran data yang kekerapannya berpandukan surat arahan semasa.",
      "Melaksanakan aktiviti pengumpulan, pengemaskinian, penyemakan (verifikasi), penentusahan dan penganalisisan data sekolah.",
      "Memastikan penyimpanan dan keselamatan data.",
      "Memastikan tarikh aktiviti pengurusan maklumat dilaksanakan mengikut jadual yang telah ditetapkan.",
      "Memastikan data dan maklumat yang dihasilkan berkualiti, sahih dan terkini.",
      "Menghasilkan laporan statistik dan maklumat pendidikan sekolah.",
      "Memaklumkan kepada PPD tentang masalah talian Internet dan penyelenggaraan peralatan ICT.",
      "Melaksanakan tindakan sebagai pembekal utama data pendidikan."
  ],
  10: [],
  11: [
      "Meneliti dan memahami semua dokumen Standard Kualiti Pendidikan Malaysia (SKPM) dan Standard Kualiti Prasekolah Kebangsaan (SKPK).",
      "Memastikan data/maklumat berkaitan sekolah dan prasekolah dikemas kini.",
      "Menyelaraskan pelaksanaan penarafan kendiri.",
      "Menyelaraskan aktiviti pengumpulan, penyemakan dan pengemaskinian maklumat berdasarkan standard yang telah ditetapkan secara berkala.",
      "Memastikan setiap ahli Pasukan Pelaksana Standard (PPS) menyedia, dan menyimpan evidens yang berkaitan dan kemas kini.",
      "Mengadakan mesyuarat sekurang-kurangnya dua (2) kali setahun.",
      "Mematuhi tarikh aktiviti pengumpulan maklumat dilaksanakan mengikut jadual yang telah ditetapkan.",
      "Membekalkan laporan SKPM dan SKPK kepada PPD, JPN atau KPM mengikut keperluan.",
      "Menyelaraskan tindakan penambahbaikan berdasarkan Laporan Kualiti SKPM dan SKPK."
  ],
  12: [
      "Mengadakan mesyuarat sekurang-kurangnya dua (2) kali setahun.",
      "Menyediakan perancangan dan mengatur strategi untuk menghadapi bencana.",
      "Memaklumkan kepada warga sekolah tentang pelan pengurusan risiko menghadapi bencana.",
      "Menyimpan dokumen dan alat berharga di tempat tinggi dan selamat.",
      "Memaklumkan perkara itu segera kepada jabatan (KPM/JPN/PPD/Polis/Bomba serta individu - PIBG dan ibu bapa) seperti yang tersenarai dalam JK Pengurusan Bencana Sekolah untuk mendapat bantuan.",
      "Memindahkan semua warga institusi ke tempat yang lebih selamat apabila bencana dijangka akan mencapai paras bahaya atau apabila diarah berpindah oleh Jawatankuasa Bencana di peringkat kebangsaan, negeri atau daerah.",
      "Mengurus penempatan murid-murid yang tempat kediaman mereka dilanda bencana agar dapat ditumpangkan murid untuk belajar di sekolah-sekolah berhampiran yang tidak terlibat sehingga bencana reda/terkawal.",
      "Mengaturkan kerja gotong royong guru-guru, staf sokongan, PIBG, penduduk setempat dan jabatan-jabatan berkaitan bagi sekolah yang dijadikan pusat penempatan sementara.",
      "Memaklumkan senarai terkini jenis dan jumlah peralatan, kerusi, meja, almari dan lain-lain yang diperlukan oleh pihak sekolah kepada JPN/PPD. Pesanan perlu dibuat dengan segera.",
      "Mengenal pasti dan menyenaraikan murid-murid yang memerlukan bantuan kewangan, buku teks, peralatan sekolah, pakaian dan keperluan sekolah yang lain dan perlu dimaklumkan ke JPN/PPD untuk mendapat bantuan tersebut.",
      "Mewujudkan bilik gerakan dan kemudahan mengumpul dan memperoleh maklumat.",
      "Menyediakan pelan tindakan menghadapi bencana banjir di peringkat sekolah.",
      "Mengurus rekod dan perkakasan penting sekolah ke tempat-tempat selamat.",
      "Memastikan sekolah mempunyai peralatan bantuan kecemasan.",
      "Mengambil langkah pencegahan dan melaporkan kes penyakit berjangkit dengan mendapatkan khidmat nasihat daripada pejabat kesihatan (semasa dan selepas bencana).",
      "Mengambil perhatian serius terhadap pengumuman Jawatankuasa Bencana Alam Negara dan Jabatan Meteorologi dari semasa ke semasa.",
      "Menyediakan bantuan dan kemudahan kepada calon-calon yang mengambil peperiksaan awam.",
      "Mengurus keperluan PdPR dari rumah atau pusat komuniti atau di mana-mana lokasi yang bersesuaian.",
      "Mengemaskinikan rekod kerosakan fizikal dan harta benda akibat bencana dalam sistem EMIS online dan melaporkan kepada PPD."
  ],
  13: [
      "Membantu pihak sekolah dalam mencapai matlamat dan kecemerlangan dalam bidang: Akademik, Kokurikulum, Disiplin murid, Sahsiah murid, Keceriaan dan keselamatan sekolah.",
      "Mewujudkan kesedaran terhadap kepentingan peranan PIBG dalam meningkatkan kecemerlangan sekolah kepada ibu bapa/penjaga dan guru-guru.",
      "Membantu memupuk kemesraan dan mewujudkan saluran komunikasi dan sosial di antara pihak sekolah dan masyarakat setempat.",
      "Merancang dan melaksanakan aktiviti yang memupuk kemesraan antara warga sekolah, ibu bapa/penjaga dan masyarakat setempat."
  ],
  14: [
      "KAJIAN TINDAKAN: Memupuk sikap menjalankan penyelidikan kajian tindakan dalam aktiviti pengajaran dan pembelajaran untuk menilai impak keberkesanan pengajaran dan pembelajaran.",
      "Menilai amalan terbaik pengajaran dan pembelajaran guru untuk dijadikan amalan guru-guru yang lain sebagai contoh terbaik.",
      "Menjalankan penyelidikan melalui kajian tindakan untuk menilai impak keberkesanan program Hal Ehwal Murid dan aktiviti Kokurikulum yang dapat dijadikan amalan terbaik sekolah.",
      "INOVASI: Menubuhkan sistem sokongan untuk guru-guru menjalankan inovasi dan seterusnya menyertai pertandingan inovasi bagi dinilai oleh orang luar mengenai prestasi inovasi yang dicipta untuk manfaat kepada murid-murid di sekolah."
  ],
  15: [
      "Menyediakan suatu penyata tahunan bagi tahun berakhir 31 Disember setiap tahun mengikut prinsip perakaunan yang diterima umum.",
      "Menyediakan penyata kewangan tahunan kepada Ketua Pusat Tanggungjawab (PTJ) yang kemudiannya dikemukakan kepada Bahagian Audit Sekolah tidak lewat dari 31 Mac tahun berikutnya.",
      "Memberi jawapan atas Laporan atau pertanyaan audit tidak lewat satu bulan dari tarikh laporan.",
      "Melantik secara bertulis seorang guru yang tidak terlibat secara langsung dalam pengurusan kewangan dan perakaunan sekolah sebagai Juruaudit Dalam untuk memastikan wujud kawalan dalaman dalam pengurusan kewangan dan perakaunan sekolah.",
      "Juruaudit Dalam bertanggungjawab menyemak rekod kewangan.",
      "Juruaudit Dalam perlu memastikan prosedur dan peraturan kewangan dipatuhi.",
      "Menyediakan laporan hasil pemeriksaan dan mengemukakan kepada Pengurus Sekolah serta membentangkan dalam Mesyuarat JPKA.",
      "JPKA bertanggungjawab membantu Pengurus Sekolah mengawasi, mengesan dan menyelia semua urusan kewangan dan akaun supaya berjalan lancar dan menepati Akta Tatacara Kewangan 1957, Arahan Perbendaharaan, Pekeliling, Surat Pekeliling dan Tatacara yang berkuatkuasa.",
      "Bidang tugas jawatankuasa meliputi pengurusan bajet, perbelanjaan, perakaunan, pungutan dan tunggakan hasil, aset dan stor, penyediaan dan pembangunan penyata kewangan.",
      "Mengadakan mesyuarat sekurang-kurangnya tiga bulan sekali selepas tamat tempoh setiap suku tahun."
  ],
  16: [
      "Sekolah hendaklah menubuhkan satu Jawatankuasa Pengurusan Aset Alih Kerajaan (JKPAK) yang dipengerusikan oleh Pengurus Sekolah untuk menyelaras pelaksanaan pengurusan aset alih.",
      "Mesyuarat JKPAK perlu diadakan sekurang-kurangnya satu (1) kali dalam tempoh tiga (3) bulan dan hasil mesyuarat hendaklah dilaporkan kepada Jawatankuasa Pengurusan Kewangan dan Akaun Sekolah. Agenda Mesyuarat JKPAK merangkumi: (a) Kedudukan semasa Aset Alih Kerajaan (b) Laporan Hasil Pemeriksaan Aset (c) Laporan Tindakan Pelupusan (d) Laporan Tindakan Surcaj/Tatatertib; dan (e) Masalah-masalah berkaitan dengan pengurusan aset.",
      "Pengurus Sekolah bertanggungjawab menamakan pegawai-pegawai yang hendak dilantik oleh Pegawai Pengawal melalui PPD ke JPN dan seterusnya kepada Kementerian: Seorang Pegawai Aset, Dua (2) orang Pegawai Pemeriksa, Dua (2) orang Lembaga Pemeriksa (KEW PA-15)"
  ],
};
