export const menuItems = [
  { id: 1, label: "PENGURUSAN KURIKULUM" },
  { id: 2, label: "PANITIA MATA PELAJARAN" },
  { id: 3, label: "HIGHLY IMMERSIVE PROGRAMME (HIP) DAN HAYYA BIL ’ARABIAH (HA)" },
  { id: 4, label: "PUSAT SUMBER SEKOLAH" },
  { id: 5, label: "PEMBELAJARAN MAYA" },
  { id: 6, label: "JADUAL WAKTU" },
  { id: 7, label: "PENTAKSIRAN DAN PEPERIKSAAN" },
  { id: 8, label: "PEMBELAJARAN ABAD KE-21 (PAK21) DAN KBAT" },
  { id: 9, label: "PENGURUSAN PENCERAPAN" },
  { id: 10, label: "PROGRAM TAHFIZ AL-SYATIBI DAN ULUL ALBAB" },
  { id: 11, label: "CARTA INDUK PENTAKSIRAN BERASASKAN SEKOLAH (PBS) SEKOLAH MENENGAH" },
];

export const committeeData: Record<number, { role: string; position: string; name: string }[]> = {
  1: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Tim. Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Naib Pengerusi 1", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi 2", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "SU Kurikulum", name: "Saemah binti Supandi" },
    { role: "AJK", position: "Penyelaras PBD", name: "Nurul Izzati binti Roslin" },
    { role: "AJK", position: "GKMP Agama", name: "Saemah binti Supandi" },
    { role: "AJK", position: "GKMP Dini", name: "Nor Azean binti Ismail" },
    { role: "AJK", position: "GKMP Bahasa", name: "Rosmawati @ Rohayati binti Hussin" },
    { role: "AJK", position: "GKMP Kemanusiaan", name: "Nooraind binti Ali" },
    { role: "AJK", position: "GKMP Sains & Mat", name: "Zahrah Khairiah Nasution binti Saleh" },
    { role: "AJK", position: "GKMP Tek & Vok", name: "Mazuin binti Mat" },
    { role: "AJK", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
    { role: "AJK", position: "Guru Data", name: "Noorlela binti Zainudin" },
    { role: "AJK", position: "Guru Perpustakaan & Media", name: "Nuurul Amira binti Razak" },
    { role: "AJK", position: "Penyelaras ICT/DELIMA", name: "Syahidatun Najihah binti Aziz" },
    { role: "AJK", position: "SU Jadual Waktu", name: "Mohamad Nasreen Hakim bin Che Mohamed" },
    { role: "AJK", position: "Penyelaras Pep. Dalaman", name: "Annur Ayuni binti Mohamed" },
    { role: "AJK", position: "Penyelaras SPM", name: "Nor Ain binti Mohamed Jori" },
    { role: "AJK", position: "Semua Ketua Panitia", name: "-" },
  ],
  2: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Setiausaha", position: "PK01 (Pengurusan Panitia)", name: "Nor Azean binti Ismail" },
    { role: "Bidang Agama", position: "KP Usul Al-Din", name: "Nor Hidayah binti Mahadun" },
    { role: "Bidang Agama", position: "KP Al-Syariah", name: "Annur Ayuni binti Mohamed" },
    { role: "Bidang Agama", position: "KP Manahij Al-’Ulum", name: "Mohd Nor bin Salikin" },
    { role: "Bidang Agama", position: "KP Tahfiz", name: "Salman bin A Rahman" },
    { role: "Bidang Dini", position: "KP LAM", name: "Norliyana binti Mhd. Amin" },
    { role: "Bidang Dini", position: "KP Al-Adab Wa Al-Balaghah", name: "Masyitah binti Razali" },
    { role: "Bidang Bahasa", position: "KP Bahasa Melayu", name: "Siti Nurul Liza binti Sidin" },
    { role: "Bidang Bahasa", position: "KP Bahasa Inggeris", name: "Nik Noorizati binti Ab Kahar" },
    { role: "Bidang Sains & Mat", position: "KP Sains", name: "Liyana binti Iskandar" },
    { role: "Bidang Sains & Mat", position: "KP Matematik", name: "Norashidah binti A Wahab" },
    { role: "Bidang Tek & Vok", position: "KP RBT", name: "Aina Fazrina binti Paing" },
    { role: "Bidang Tek & Vok", position: "KP Perniagaan", name: "Nurul Syafiqah binti Husin" },
    { role: "Bidang Kemanusiaan", position: "KP Sejarah", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
    { role: "Bidang Kemanusiaan", position: "KP Geografi", name: "Nurul Izzati binti Roslin" },
    { role: "Bidang Kemanusiaan", position: "KP Pend. Seni Visual", name: "Syahidatun Najihah binti Aziz" },
    { role: "Bidang Kemanusiaan", position: "KP PJPK", name: "Mohd Nur bin Ahmad" },
  ],
  3: [
    { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Tim. Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Penyelaras", position: "Hayya Bil ‘Arabiah (HA)", name: "Nor Azean binti Ismail" },
    { role: "Penyelaras", position: "Highly Immersive Prog (HIP)", name: "Nooraind binti Ali" },
    { role: "Setiausaha", position: "Hayya Bil ‘Arabiah (HA)", name: "Norliyana binti Mhd. Amin" },
    { role: "Setiausaha", position: "Highly Immersive Prog (HIP)", name: "Mohamad Nasreen Hakim bin Che Mohamed" },
    { role: "AJK", position: "Penyelaras Tingkatan 1", name: "Мohammad Firros Bin Rosool Gani" },
    { role: "AJK", position: "Penyelaras Tingkatan 2", name: "Ahmad Fikruddin bin Ahmad Raza'i" },
    { role: "AJK", position: "Penyelaras Tingkatan 3", name: "Siti Aminah binti Mohamed" },
    { role: "AJK", position: "Penyelaras Tingkatan 4", name: "Nik Noorizati binti Ab Kahar" },
    { role: "AJK", position: "Penyelaras Tingkatan 5", name: "Norashidah binti A Wahab" },
    { role: "AJK", position: "Penyelaras Tahfiz", name: "Salman bin A Rahman" },
  ],
  4: [
    { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Tim. Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Penyelaras", position: "Penyelaras Pengawas & Pusat Sumber", name: "Nuurul Amira binti Razak" },
    { role: "Pembantu PSS", position: "Setiausaha Jawatankuasa Pusat Sumber Sekolah (Pembantu)", name: "Syahidatun Najihah binti Aziz" },
    { role: "AJK", position: "Semua Ketua Panitia", name: "-" },
    { role: "AJK", position: "Guru Perpustakaan", name: "Nuurul Amira binti Razak" },
    { role: "AJK", position: "Penyelaras NILAM", name: "Syahidatun Najihah binti Aziz" },
    { role: "AJK", position: "Guru Bahan Bantu Mengajar", name: "Nor Azean binti Ismail" },
    { role: "AJK", position: "Guru Pengendali Alat Pandang Dengar/Unit Teknologi", name: "Nor Ain binti Mohamed Jori" },
    { role: "AJK", position: "Penyelaras ICT/DELIMA", name: "Syahidatun Najihah binti Aziz" },
  ],
  5: [
    { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Tim. Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "Penyelaras ICT/DELIMA", name: "Syahidatun Najihah binti Aziz" },
    { role: "AJK", position: "Guru Bimbingan & Kaunseling", name: "Muhammad Hafiz bin Jalil" },
    { role: "AJK", position: "Semua GKMP", name: "-" },
    { role: "AJK", position: "Penyelaras NILAM", name: "Syahidatun Najihah binti Aziz" },
    { role: "AJK", position: "Semua Ketua Panitia", name: "-" },
    { role: "AJK", position: "Semua Guru Mata Pelajaran", name: "-" },
  ],
  6: [
    { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Tim. Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Penyelaras", position: "Penyelaras Jadual Waktu", name: "Salman bin A Rahman" },
    { role: "Setiausaha", position: "Setiausaha Jadual Waktu", name: "Mohamad Nasreen Hakim bin Che Mohamed" },
    { role: "AJK", position: "GKMP Agama", name: "Saemah binti Supandi" },
    { role: "AJK", position: "GKMP Dini", name: "Nor Azean binti Ismail" },
    { role: "AJK", position: "GKMP Bahasa", name: "Rosmawati @ Rohayati binti Hussin" },
    { role: "AJK", position: "GKMP Kemanusiaan", name: "Nooraind binti Ali" },
    { role: "AJK", position: "GKMP Sains & Matematik", name: "Zahrah Khairiah Nasution binti Saleh" },
    { role: "AJK", position: "GKMP Teknik & Vokasional", name: "Mazuin binti Mat" },
    { role: "AJK", position: "Semua Ketua Panitia", name: "-" },
  ],
  7: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi 1", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Timbalan Pengerusi 2", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Timbalan Pengerusi 3", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "Penyelaras PBD", name: "Siti Nurul Liza binti Sidin" },
    { role: "AJK", position: "Setiausaha PBD Menengah Atas", name: "Nurul Izzati binti Roslin" },
    { role: "AJK", position: "Setiausaha Sijil Pelajaran Malaysia (SPM)", name: "Nor Ain binti Mohamed Jori" },
    { role: "AJK", position: "Setiausaha Sijil Menengah Agama (SMA)", name: "Nor Hidayah binti Mahadun" },
    { role: "AJK", position: "Setiausaha Sijil Menengah Rendah Agama (SMRA)", name: "Siti Aminah binti Mohamed" },
    { role: "AJK", position: "Setiausaha Peperiksaan Dalaman", name: "Annur Ayuni binti Mohamed" },
    { role: "AJK", position: "Semua GKMP", name: "-" },
    { role: "AJK", position: "Semua Panitia", name: "-" },
    { role: "AJK", position: "Semua Guru Mata Pelajaran", name: "-" },
  ],
  8: [
    { role: "Pengerusi", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Timbalan Pengerusi 1", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Timbalan Pengerusi 2", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Timbalan Pengerusi 3", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "GKMP Kemanusiaan", name: "Nooraind binti Ali" },
    { role: "AJK Pasukan Pemandu", position: "Semua GKMP", name: "-" },
    { role: "AJK Pasukan Pemandu", position: "Semua Panitia", name: "-" },
    { role: "AJK Pasukan Pemandu", position: "Semua Guru Kelas", name: "-" },
    { role: "AJK Pasukan Pemandu", position: "Semua Guru Mata Pelajaran", name: "-" },
  ],
  9: [
    { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Tim. Pengerusi", position: "GPK Hal Ehwal Murid", name: "Shaharer bin Hj Husain" },
    { role: "Naib Pengerusi", position: "GPK Kokurikulum", name: "Zulkifli bin Md Aspan" },
    { role: "Setiausaha", position: "PK04 (Pengurusan Pencerapan)", name: "Rosmawati @ Rohayati binti Hussin" },
    { role: "AJK", position: "PK06 (Pengurusan Semakan Hasil Kerja Murid)", name: "Mohamad Nasreen Hakim bin Che Mohamed" },
    { role: "AJK", position: "Penyelaras MBM", name: "Siti Nurul Liza binti Sidin" },
    { role: "AJK", position: "Penyelaras MBI", name: "Nik Noorizati binti Ab Kahar" },
    { role: "AJK", position: "Semua GKMP", name: "-" },
    { role: "AJK", position: "Semua Ketua Panitia", name: "-" },
  ],
  10: [
    { role: "Penasihat", position: "Pengetua", name: "Zulkeffle bin Muhammad" },
    { role: "Pengerusi", position: "GPK Pentadbiran", name: "Noratikah binti Abd. Kadir" },
    { role: "Setiausaha", position: "Penyelaras Isbat Tahfiz / KKQ", name: "Salman bin A Rahman" },
    { role: "AJK", position: "Penyelaras Tahfiz Al-Syatibi", name: "Muhammad Zaid bin Zamzuri" },
    { role: "AJK", position: "Penolong Penyelaras Tahfiz Syatibi", name: "Ali bin A Rahman" },
    { role: "AJK", position: "Penyelaras Isbat Tahfiz / KKQ", name: "Salman bin A Rahman" },
    { role: "AJK", position: "Penolong Penyelaras KKQ", name: "Muhammad Zaid bin Zamzuri" },
  ],
  11: []
};

export const tasksData: Record<number, string[]> = {
  1: [
    "Mengadakan mesyuarat sekurang-kurang empat (4) kali setahun.",
    "Menentukan dasar dan hala tuju pengurusan kurikulum sekolah.",
    "Merancang dan mengurus pengoperasian kurikulum di sekolah.",
    "Merancang dan mengawal pengurusan sumber berkaitan kurikulum di sekolah.",
    "Mengenal pasti dan menyelesaikan isu dan permasalahan berkaitan kurikulum di sekolah.",
    "Merancang, memantau, menilai dan menambah baik pelaksanaan program dan aktiviti kurikulum di sekolah.",
    "Membina hubungan seranta dengan ibu bapa, komuniti dan pihak yang berkepentingan.",
    "Melaporkan dan mendokumenkan program dan aktiviti berkaitan kurikulum di sekolah.",
    "Mengurus dan menyelia pengoperasian bilik khas berkaitan kurikulum.",
    "Merancang, menyusun dan melaksanakan program-program dan aktiviti-aktiviti untuk meningkatkan tahap pencapaian sekolah di bidang pengurusan, akademik, kemenjadian murid, kokurikulum dan keceriaan.",
    "Membuat penilaian kendiri tahap pencapaian sekolah berdasarkan keputusan Pelaporan Sekolah.",
    "Melaksanakan tugas PPS di bawah komponen terlibat untuk mengurus pelaporan SKPMg2.",
    "Melaksanakan amalan MMI."
  ],
  2: [
    "PENGURUSAN PANITIA:",
    "Menentukan penggunaan DSKP yang dikemas kini.",
    "Menentukan penggunaan alat bantu mengajar dan kaedah-kaedah pengajaran/pembelajaran yang dikemas kini.",
    "Bertanggungjawab menyediakan rancangan pengajaran tahunan.",
    "Menyelaraskan penyediaan soalan-soalan peperiksaan dalaman dan pemeriksaan kertas-kertas jawapan.",
    "Menganalisis keputusan peperiksaan dan mengkaji serta mencari jalan untuk memajukan tahap pencapaian dari semasa ke semasa.",
    "Menentukan jenis-jenis buku yang perlu ada di sekolah (perpustakaan) untuk rujukan guru.",
    "Memberi kerjasama kepada jawatankuasa SPBT untuk menjaga keselamatan buku-buku teks yang digunakan.",
    "Bertanggungjawab menyediakan bahan-bahan atau alat-alat untuk pameran, jika diperlukan.",
    "Mengkaji dan menentukan jenis buku latihan/buku kerja bagi setiap kelas, jika diperlukan.",
    "Mengadakan tindak balas kepada setiap perubahan baharu yang diperlukan seperti sukatan baru, kaedah pengajaran dan pembelajaran baru, jika ada.",
    "Membuat anggaran perbelanjaan tahunan dengan persetujuan pihak sekolah.",
    "Bersama-sama memikul tanggungjawab mengekalkan dan meningkatkan prestasi murid-murid.",
    "Melaksanakan peraturan-peraturan panitia sedia ada.",
    "Mengadakan mesyuarat panel sekurang-kurangnya sekali dalam sepenggal atau lebih kerap, jika perlu.",
    "Memastikan penyeliaan penyemakan buku latihan murid dilaksanakan sekurangkurangnya dua (2) kali setahun.",
    "Merancang dan melaksanakan program-program serta intervensi untuk kemajuan murid dan program di bawah arahan KPM.",
    "PENGOPERASIAN PdPc:",
    "Bersama Ketua Panitia merancang ketetapan yang menjadi pegangan Komponen Pengurusan Kurikulum Sekolah.",
    "Memastikan semua data pentaksiran setiap tahun dikumpul dan dianalisa untuk digunakan dalam perancangan tahun semasa.",
    "Memastikan analisa headcount dibuat untuk digunakan dalam perancangan PdPc oleh guru-guru mengikut mata pelajaran.",
    "Memastikan pencerapan dijalankan dan menganalisa semua dapatan pencerapan untuk menambah baik pengoperasian PdPc.",
    "Memastikan guru-guru merancang dan melaksanakan intervensi dalam PdPc untuk menghasilkan PdPc cemerlang.",
    "Memastikan guru-guru melaksanakan pemulihan, pengukuhan dan pengayaan di dalam bilik darjah.",
    "Memastikan tugasan disemak oleh guru-guru dan pembetulan dilaksanakan sebagai penambahbaikan PdPc."
  ],
  3: [
    "Mengadakan mesyuarat jawatankuasa minimum 4 kali setahun.",
    "Merancang dan melaksanakan program peningkatan penggunaan Bahasa Arab dan Bahasa Inggeris di kalangan guru dan murid seperti mukhaiyyam arabi dan lain-lain.",
    "Menilai dan melaporkan keberkesanan program yang dilaksanakan.",
    "Menetapkan sasaran pencapaian program BA dan BI.",
    "Menjalankan tindakan susulan bagi meningkatkan kecemerlangan penggunaan Bahasa Arab dan Bahasa Inggeris.",
    "Melaksanakan program ’Tahbibul Lughah’ bagi aktiviti Bahasa Arab dan ’I love English’ bagi aktiviti Bahasa Inggeris sepanjang tahun.",
    "Melaksanakan program khitobah dan public speaking."
  ],
  4: [
    "SENARAI TUGAS JAWATANKUASA INDUK:",
    "(A1) PENGERUSI:",
    "Sebagai ketua pentadbir pengurus dan mempengerusikan mesyuarat AJK induk PSS.",
    "Memastikan PSS berjalan dengan berkesannya demi mencapai objektif-objektif PSS yang telah dirangka.",
    "Membentuk dasar yang praktikal mengenai perkhidmatan media di sekolah dan menyelaraskan kegiatan-kegiatan ini dengan PSS yang lain dengan bantuan Unit Sumber Teknologi Pendidikan (USTP).",
    "Merancang dan melaksanakan program untuk mendapatkan alat atau media serta kemudahan-kemudahan lain untuk memenuhi keperluan-keperluan pendidikan yang progresif.",
    "Menyelaraskan kursus-kursus dalam perkhidmatan bagi guru-guru yang berminat, berbakat dan memerlukan.",
    "Mengadakan perbincangan dengan para pegawai USTP pelbagai peringkat mengenal program media pendidikan di sekolah.",
    "Merancang belanjawan tahunan dan belanjawan jangka panjang dengan kerjasama AJK PSS lain.",
    "Membuat penilaian yang berterusan terhadap kegiatan-kegiatan pengajaran dan pembelajaran berasaskan sumber di sekolah.",
    "Menjalankan penyelidikan dan percubaan mengenai penggunaan media baharu dan yang selalu digunakan dengan kerjasama USTP.",
    "Menyediakan kemudahan membaiki dan mengendalikan alat-alat pengajaran dan pembelajaran.",
    "Melahirkan satu budaya yang boleh menggalakkan guru-guru dan murid-murid untuk menggunakan bahan-bahan dalam proses pengajaran dan pembelajaran melalui PSS merentasi kurikulum.",
    "Menyebarkan konsep PSS kepada guru-guru, murid-murid dan masyarakat tempatan.",
    "Sentiasa peka dengan perkembangan teknologi dalam pendidikan dan maklumat terkini.",
    "Dapat menerima perubahan dalam pendidikan dengan fikiran terbuka dari semasa ke semasa.",
    "(A2) PENYELARAS PSS:",
    "Menyelaraskan semua program media yang dirancang dan memastikan agar dapat dilaksanakan.",
    "Membantu menggariskan matlamat, objektif dan perancangan dasar yang akan dilaksanakan oleh PSS.",
    "Memantau dan memastikan program-program pembangunan serta perancangan aktiviti agar dilaksanakan dengan cemerlangnya.",
    "Menyediakan senarai semak tugas untuk memastikan perkembangan dan tindak ikut perancangan dan pembangunan PSS.",
    "Menyediakan anggaran perbelanjaan tahunan PSS dengan kerjasama semua AJK Kerja PSS.",
    "Mengurus dan mengelolakan semua kemudahan fizikal dan perkhidmatan yang disediakan oleh PSS.",
    "Memilih dan memesan bahan-bahan perlu dan yang bersesuaian untuk keperluan masyarakat sekolah dengan kerjasama guru-guru.",
    "Memberikan khidmat nasihat dan kepakaran kepada pihak yang memerlukan.",
    "Bekerjasama dengan pihak-pihak bertanggungjawab dalam merancang dan melaksanakan program perkembangan staf.",
    "Menggalakkan guru dan murid untuk menpelbagai media dalam pendidikan.",
    "Mendapatkan peruntukan perbelanjaan pengurus pembangunan PSS.",
    "Menganjurkan sesi promosi yang bersesuaian untuk menggalakkan budaya penggunaan perkhidmatan disediakan oleh PSS.",
    "Bertindak sebagai penghubung antara pihak sekolah dengan agensi-agensi kerajaan dan swasta dalam perkara yang berkaitan dengan aktiviti PSS.",
    "Memastikan penyediaan rekod-rekod yang lengkap untuk tujuan penyemakan oleh pegawai-pegawai pendidikan yang melakukan lawatan.",
    "Menyediakan laporan tahunan PSS.",
    "Mendapatkan maklum balas dan cadangan-cadangan bagi meningkatkan mutu perkhidmatan yang disediakan oleh PSS.",
    "Membuat penilaian dan kaji selidik tentang keberkesanan penggunaan semua perkhidmatan yang disediakan oleh PSS.",
    "Menyediakan senarai semak yang bersesuaian untuk memastikan semua tugas yang berkaitan telah dirancang dan dilaksanakan.",
    "Melaksanakan tugas lain yang diarahkan oleh PGB/pentadbir dari semasa ke semasa.",
    "(A3) KETUA PANITIA MATA PELAJARAN:",
    "Merancang supaya dapat membudayakan penggunaan media pengajaran dan pembelajaran di kalangan guru dan murid-murid di sekolah.",
    "Menyebarkan maklumat-maklumat terkini tentang teknologi pendidikan kepada semua guru untuk tujuan pengajaran dan pembelajaran yang berkesan.",
    "Membantu AJK PSS dalam pemilihan bagi mendapatkan alat dan bahan pengajaran yang bersesuaian untuk kegunaan guru dan murid.",
    "Membantu dan merancang agar guru-guru dapat membina alat dan bahan pengajaran dengan menggunakan pendekatan bersistem.",
    "Menilai keberkesanan alat dan media pengajaran yang dibeli ataupun yang dihasilkan sendiri.",
    "Mewakili PSS dalam semua aktiviti perkembangan kurikulum sekolah.",
    "Menyediakan senarai semak yang bersesuaian untuk memastikan semua tugas yang berkaitan telah dirancang dan dilaksanakan.",
    "Membantu dan menjalankan tugas yang berkaitan dengan PSS seperti yang diarahkan oleh PGB/pentadbir sekolah.",
    "(B) SENARAI TUGAS JAWATANKUASA KERJA:",
    "(B1) GURU PERPUSTAKAAN:",
    "Menentukan dasar pentadbiran, pembelian dan penggunaan perpustakaan.",
    "Melatih dan menyelia petugas-petugas perpustakaan untuk membantu pengurusan perpustakaan.",
    "Memastikan bahawa perpustakaan diurus dengan teraturnya dan bersistematik.",
    "Merancang dan melaksanakan aktiviti-aktiviti perpustakaan.",
    "Merancang anggaran belanjawan tahunan perpustakaan.",
    "Menyimpan rekod-rekod yang berkaitan dengan pengurusan perpustakaan yang bersistem.",
    "Memberikan khidmat nasihat dan kepakaran kepada guru-guru dan murid-murid yang memerlukan.",
    "Memperoleh dan menyemak alat-alat perolehan (bibliografi, katalog penerbit, senarai tajuk dan lain-lain) untuk memilih mengetahui jenis-jenis dan tajuk-tajuk buku yang perlu dibeli untuk menambahkan koleksi di perpustakaan.",
    "Menjalankan kerja menyemak stok pada hujung tahun.",
    "Mengelas dan mengkatalog bahan-bahan dari koleksi.",
    "Menyediakan katalog yang dikemas kini untuk kemudahan rujukan guru-guru dan murid-murid yang memerlukan.",
    "Menyediakan jadual waktu penggunaan perpustakaan yang praktikal dan berkesan.",
    "Melantik pengawas PSS dan mengadakan program-program latihan yang bersesuaian dengan keperluan.",
    "Membantu mengurus semua program media PSS yang berkaitan dengan perkhidmatan perpustakaan.",
    "Membantu murid-murid untuk memilih buku-buku dan bahan yang bersesuaian untuk bacaan dan rujukan.",
    "Mengadakan sesi tunjuk ajar kepada murid-murid tentang cara-cara memaksimumkan penggunaan perpustakaan demi peningkatan akademik.",
    "Menyediakan Senarai Semak yang bersesuaian untuk memastikan semua tugas yang berkaitan telah dirancang dan dilaksanakan.",
    "Membantu dan menjalankan tugas yang berkaitan dengan PSS seperti yang diarahkan oleh PGB/pentadbir sekolah dari semasa ke semasa.",
    "(B2) GURU NILAM:",
    "Membantu GPM merancang dan melaksanakan aktiviti program NILAM peringkat sekolah.",
    "Menyimpan segala rekod, minit mesyuarat dan surat menyurat.",
    "Menyelaraskan perjalanan mesyuarat dan hal-hal yang berkaitan.",
    "Mempamer data dan maklumat di Sudut NILAM yang wujud di sekolah.",
    "Mengumpulkan maklumat kertas kerja, laporan dan bahan serta menyerahkannya kepada pihak pentadbir.",
    "Menyediakan laporan berkala dan laporan tahunan bertulis untuk dikemukakan kepada Penyelaras Program dan salinan kepada pengerusi.",
    "Menyemak dan mengesahan rekod bacaan NILAM.",
    "Membantu dan menjalankan tugas yang berkaitan dengan PSS seperti yang diarahkan oleh PGB/pentadbir sekolah dari semasa ke semasa.",
    "(B3) GURU BAHAN BANTU MENGAJAR:",
    "Mencatatkan semua bekalan alat perkakasan (hardware) dan bahan-bahan perisian (software) yang dibeli atau diterima ke dalam buku stok alat bantu mengajar.",
    "Mengelaskan dan mengkatalogkan semua bahan perisian yang dibeli atau diterima.",
    "Menyediakan dan mengedarkan katalog alat bantu mengajar dari semasa ke semasa untuk pengetahuan guru-guru dan murid-murid yang memerlukan.",
    "Mengadakan sesi perkembangan staf dalam pembinaan media kos rendah dan praktikal serta untuk menggalakkan penggunaan media pengajaran pembelajaran yang bersesuaian oleh guru-guru dan murid-murid.",
    "Menasihati dan membimbing guru-guru serta murid-murid tentang kaedah memilih jenis-jenis media yang bersesuaian, praktikal dan berkesan untuk pengajaran dan pembelajaran.",
    "Mewujudkan budaya pinjaman dan penggunaan alat dan bahan bantu mengajar yang sistematik dan berkesan khususnya bagi keperluan pengajaran guru-guru.",
    "Mengadakan promosi bagi menggalakkan penggunaan ABM dari semasa ke semasa untuk makluman guru dan murid.",
    "Melaporkan sebarang kerosakan alat-alat perkakasan atau perisian kepada Penyelaras PSS supaya tindakan segera boleh dilakukan untuk penggantian dan pembaikan.",
    "Menentukan bahawa semua peralatan bantu mengajar agar sentiasa dalam keadaan baik untuk digunakan.",
    "Menyediakan buku-buku rekod yang perlu untuk memudahkan penyemakan oleh pihak pengurusan ataupun bagi tujuan semakan oleh pegawai-pegawai pendidikan yang memerlukannya.",
    "Menentukan supaya Buku Rekod Penggunaan disediakan untuk kemudahan para pengguna membuat catatan penggunaan yang perlu.",
    "Menyediakan Senarai Semak yang bersesuaian untuk memastikan semua tugas yang berkaitan telah dirancang dan dilaksanakan.",
    "Membantu dan menjalankan tugas yang berkaitan dengan PSS seperti yang diarahkan oleh PGB/pentadbir sekolah dari semasa ke semasa.",
    "(B4) GURU PENGENDALI ALAT PANDANG DENGAR/UNIT TEKNOLOGI:",
    "Menggalakkan pembudayaan penggunaan media teknologi pendidikan terutamanya alat dan bahan tayangan, rakaman serta penggunaan nota-nota yang bersesuaian untuk digunakan.",
    "Membina koleksi pita-pita video dan audio atau sumber-sumber teknologi pendidikan yang bersesuaian untuk kegunaan guru dan murid-murid dalam pengajaran dan pembelajaran.",
    "Berusaha mengambil tindak ikut untuk mempertingkatkan penggunaan APD.",
    "Menyediakan jadual penggunaan, statistik ataupun mempamerkan bahanbahan yang bersesuaian bagi memastikan kecemerlangan perkhidmatan yang disediakan.",
    "Menyediakan dan mengedarkan katalog alat bantu mengajar dari semasa ke semasa untuk pengetahuan guru-guru dan murid-murid yang memerlukan.",
    "Melaporkan sebarang kerosakan alatan supaya segera dibaik pulih dengan secepat mungkin.",
    "Merancang anggaran belanjawan tahunan bagi penyediaan perkhidmatan TV Pendidikan dan Radio Pendidikan.",
    "Merancang dan menjalankan program-program yang bersesuaian untuk meningkatkan penggunaan APD secara berkesan.",
    "Menyediakan catatan dalam buku-buku laporan tentang sebarang aktiviti yang telah dijalankan untuk tujuan penyemakan dan rekod.",
    "Menyediakan senarai semak yang bersesuaian untuk memastikan semua tugas yang berkaitan telah dirancang dan dilaksanakan.",
    "Membantu dan menjalankan tugas yang berkaitan dengan PSS seperti yang diarahkan oleh PGB/pentadbir sekolah dari semasa ke semasa.",
    "(B5) GURU KHIDMAT KOMPUTER/GURU ICT:",
    "Menentukan dasar pentadbiran, pembelian dan pengurusan komputer termasuk keperluan-keperluan semasanya.",
    "Mempunyai catatan (Buku Stok) semua perbekalan alatan atau perkakasan serta perisian (software) seperti komputer, kertas, dakwat dan lain-lain.",
    "Bertanggungjawab untuk melatih pelanggan etika penggunaan komputer dan kerahsiaan data serta membudayakan penggunaan komputer melalui program literasi komputer yang bersesuaian.",
    "Menggalakkan penggunaan komputer untuk tugas-tugas pengajaran dan pembelajaran.",
    "Berusaha mengelas dan mengkatalog media storan yang dimiliki.",
    "Merancang aktiviti unit komputer.",
    "Menyediakan keperluan operasi yang sistematik seperti jadual waktu, rekod penggunaan dan lain-lain.",
    "Melaporkan sebarang kerosakan supaya dapat dilakukan tindakan baik pulih atau penggantian dengan kadar segera.",
    "Menyediakan senarai semak yang bersesuaian  untuk memastikan semua tugas yang berkaitan telah dirancang dan dilaksanakan.",
    "Membantu dan menjalankan tugas yang berkaitan dengan PSS seperti yang diarahkan oleh PGB/pentadbir sekolah dari semasa ke semasa.",
    "(C)  SENARAI TUGAS PEMBANTU PSS:",
    "URUSAN AM:",
    "Mengawal PSS semasa dibuka",
    "Menyusun buku, menjaga kebersihan PSS",
    "PINJAMAN:",
    "Mengurus hal pinjaman, menyemak buku yang dipulangkan",
    "Membuat notis peringatan kepada peminjam yang lewat memulangkan buku",
    "Menyediakan analisis pinjaman",
    "PEMBELIAN:",
    "Menyediakan senarai pesanan",
    "Menaip surat",
    "Menyemak bahan yang baru dibeli",
    "MEMPROSES BUKU:",
    "Menulis nombor perolehan dan nombor panggilan",
    "Menyediakan kocek, kad buku dan slip tarikh pulang",
    "Membalut buku dan lain lain",
    "MEMPERBAIKI BUKU:",
    "Membaik pulih buku yang rosak atau koyak",
    "Menjilid majalah dan lain-lain yang perlu",
    "FAIL TEGAK:",
    "Menyediakan keratan akhbar, gambar-gambar, brosur dan sebagainya.",
    "MENAIP:",
    "Pengautomasian PSS",
    "REKOD:",
    "Merekodkan dan menyimpan mengenai bahan-bahan dan kewangan PSS",
    "Mengurus penyemakan stok",
    "SERANTA:",
    "Menyediakan bahan pameran, papan kenyataan dan sebagainya."
  ],
  5: [
    "Menyelaraskan pelaksanaan segala perancangan pembelajaran menggunakan pelantar maya yang dikuatkuasakan.",
    "Mengurus latihan dan kursus dalaman berkaitan aplikasi dan juga kaedah pembelajaran berkaitan penggunaan ICT.",
    "Merancang aktiviti pembudayaan pembelajaran berasaskan ICT melalui programprogram khas yang melibatkan semua warga sekolah.",
    "Menyediakan jadual penggunaan makmal dan memastikan penggunaan dengan berkesan.",
    "Menyediakan prosedur kerja untuk memastikan semua pengguna mengetahui, memahami dan  mematuhi langkah-langkah keselamatan.",
    "Mengumpulkan bahan pembelajaran untuk dijadikan koleksi sekolah."
  ],
  6: [
    "Menentukan bilangan kelas dan kelayakan guru.",
    "Menyediakan peruntukan waktu mengajar mengikut mata pelajaran.",
    "Pengagihan mata pelajaran dan bilangan waktu yang sesuai.",
    "Menentukan kesesuaian masa untuk mata pelajaran tertentu.",
    "Menentukan penggunaan bengkel dan makmal.",
    "Menentukan guru kelas berdasarkan kelas yang diajar.",
    "Memastikan jadual waktu induk dan persendirian disediakan pada waktu ditentukan",
    "Membuat pindaan jika perlu.",
    "Memastikan salinan jadual waktu dihantar kepada PGB dan dipaparkan untuk makluman semua.",
    "Melaksanakan tugas-tugas lain yang diarahkan oleh pihak pentadbir dari semasa  ke semasa."
  ],
  7: [
    "Bidang Tugas semua setiausaha dalaman:",
    "Merancang ujian dan peperiksaan di peringkat sekolah berpandukan perancangan Takwim Peperiksaan Sekolah.",
    "Menyusun Jadual Peperiksaan, tarikh kertas soalan siap, tarikh pemarkahan dan penyerahan markah kepada guru tingkatan dan Pengetua/Penolong Kanan.",
    "Memastikan kertas peperiksaan disediakan, ditandatangani dan dihantar untuk dicetak.",
    "Menyediakan Jadual Ujian dan Jadual Peperiksaan dalaman berpandukan Takwim Peperiksaan Sekolah.",
    "Memantau kemasukan markah ujian / peperiksaan ke dalam idMe.",
    "Membuat analisis peperiksaan dan membentangkan analisis peperiksaan dalam Mesyuarat Kajian Semula.",
    "Menyediakan analisis keputusan Headcount bagi Ujian (OTI 1), Peperiksaan Pertengahan (OTI 2)  dan Peperiksaan Akhir Tahun (OT 3).",
    "Melengkapkan Markah Ujian 1 (OTI 1), Peperiksaan Pertengahan (OTI 2) dan Peperiksaan Akhir Tahun (OT 3) untuk serahan kepada Penolong Kanan (2 salinan) dan pemfailan.",
    "Setiausaha menyediakan Jadual Pencatat Minit Mesyuarat Post-Mortem (Peperiksaan Pertengahan  dan Akhir/Percubaan) mengikut giliran dan diserahkan kepada Penolong Kanan 2 minggu selepas sesi persekolahan bermula.",
    "Setiausaha (pencatat minit) perlu mendapatkan agenda mesyuarat, mengedar Surat Panggilan Mesyuarat dan minit mesyuarat yang lalu. Edar senarai kehadiran (semasa mesyuarat).",
    "Setiausaha perlu memastikan tempat mesyuarat, komputer, PA dalam keadaan sedia untuk digunakan.",
    "Bidang Tugas Setiausaha Peperiksaan SPM:",
    "Merancang ujian dan peperiksaan di peringkat sekolah berpandukan perancangan LPM.",
    "Memilih guru sebagai pengawas (ketua & penolong).",
    "Setiausaha SPM mengurus pendaftaran masuk peperiksaan.",
    "Memberi penerangan mengenai peperiksaan awam kepada murid dan guru.",
    "Menyediakan tempat peperiksaan dan peralatan diperlukan.",
    "Mengambil dan mengagih bahan-bahan peperiksaan awam kepada 2 pusat peperiksaan.",
    "Setiausaha SPM dikehendaki berada di sekolah 1 minggu sebelum dan selepas peperiksaan awam dijalankan supaya membantu Ketua Pengawas jika ada sebarang masalah pendaftaran murid.",
    "Setiausahamemastikan pusat peperiksaan dan bilik simpanan bahan sedia untuk digunakan.",
    "Setiausaha Mendapatkan kunci-kunci bilik/almari daripada Ketua Pengawas serta soalan peperiksaan untuk  simpanan sekolah.",
    "Membuat analisis keputusan peperiksaan SPM untuk dibentangkan dalam Mesyuarat Kajian  Semula.",
    "Setiausaha SPM menyediakan analisis keputusan Headount bagi Peperiksaan Pertengahan (OTI 1) dan  Percubaan (OTI 2) untuk serahan ke JPN dan difailkan."
  ],
  8: [
    "Mewujudkan suasana pembelajaran abad ke-21 di dalam dan luar kelas.",
    "Memastikan PdP guru menjurus ke arah pembelajaran abad ke-21.",
    "Membantu guru melengkapkan diri melalui latihan dalaman dan luaran berkenaan               pembelajaran abad ke-21.",
    "Mewujudkan dan membentuk suasana kemahiran berfikir aras tinggi dalam persekitaran sekolah."
  ],
  9: [
    "Bertujuan untuk mempertingkat keberkesanan proses pembelajaran dan pengajaran.",
    "Menyediakan jadual pencerapan guru dua kali setahun.",
    "Memastikan semua guru dicerap PdPc dalam bilik darjah sekurang-kurangnya dua kali setahun.",
    "Memastikan guru-guru dicerap mampu mencapai markah 80% ke atas.",
    "Membuat analisis dapatan data pencerapan guru.",
    "Memastikan laporan ADaPPS dihantar ke PPD dua kali setahun (Mei dan September)."
  ],
  10: [
    "Melatih murid Tahfiz ke arah pembudayaan Al-Quran.",
    "Menguruskan Hal Ehwal Madrasah Tahfiz.",
    "Menguruskan program Tahfiz Al-Syatibi  dan Tahfiz Ulul-Albab."
  ],
  11: [
    "PENTAKSIRAN BERASASKAN SEKOLAH (PBS):",
    "(A1) ASPEK PENGURUSAN:",
    "Menubuhkan jawatankuasa penjaminan kualiti PBS yang melibatkan aktiviti pementoran, pemantauan, pengesanan dan penyelarasan.",
    "Memastikan semua murid memiliki pelaporan akhir PBS.",
    "Memastikan pentaksiran dijalankan sepanjang pengajaran dan pembelajaran.",
    "Menyediakan dan memantau perjalanan pentaksiran dan pelaporan dua (2) kali setahun.",
    "Memastikan penyelarasan skor di peringkat sekolah dilaksanakan.",
    "Memastikan pentaksir memaklumkan skor kepada murid dan ibu bapa/penjaga yang ditaksir dan murid menandatangani borang skor individu bagi setiap pentaksiran.",
    "Memastikan pentaksir melaporkan tahap penguasaan murid dalam PBD menggunakan templat pelaporan secara luar talian yang digunakan mengikut tahun semasa di peringkat sekolah, serta dilaporkan kepada murid dan ibu bapa.",
    "Menyediakan fail pengurusan PBS.",
    "Menyediakan laporan pencerapan dan pemantauan.",
    "Menyediakan analisis pentaksiran keseluruhan.",
    "(A2) SPEK PENJAMINAN KUALITI PBS:",
    "1. JK PEMENTORAN:",
    "Memberikan pengetahuan, kefahaman dan kemahiran mengenai prosedur dan garis panduan kepada guru.",
    "Meningkatkan kompetensi dan keyakinan guru.",
    "Membimbing dan membantu guru menyelesaikan masalah.",
    "Meningkatkan profesionalisme dan kualiti kerja guru.",
    "JK PEMANTAUAN:",
    "Memastikan PBS dilaksanakan mengikut prosedur dan garis panduan.",
    "Mengenal pasti masalah pelaksanaan PBS.",
    "Membantu menyelesaikan masalah pelaksanaan PBS.",
    "Mengelakkan berlakunya penyelewengan dan ketidakakuran dalam pelaksanaan PBS.",
    "Menyediakan laporan pelaksanaan PBS untuk tujuan penambahbaikan.",
    "JK PENGESANAN:",
    "Memastikan instrumen pentaksiran menepati dokumen kurikulum.",
    "Memastikan item yang dibina sesuai dengan konstruk yang diukur.",
    "Memastikan item yang dibina menepati prinsip pembinaan item.",
    "Memastikan item yang dibina sesuai dengan tahap penguasaan murid.",
    "Memastikan item menggunakan laras bahasa yang sesuai.",
    "Memastikan masa yang diperuntukkan mencukupi.",
    "Memastikan kebolehtadbiran dan kebolehlaksanaan   instrumen pentaksiran.",
    "Mencadangkan penambahbaikan instrumen pentaksiran.",
    "JK PENYELARASAN:",
    "Menyelaraskan pengetahuan dan kefahaman guru terhadap panduan penskoran.",
    "Memastikan guru memeriksa hasil kerja murid berdasarkan panduan penskoran.",
    "Memastikan skor yang diberikan menepati keupayaan sebenar murid.",
    "Memastikan kesahan dan kebolehpercayaan skor.",
    "Memastikan skor yang diberikan adalah adil bagi semua murid."
  ]
};
